EOS-12962: Set Lyve Rack serial number
Signed-off-by: sradhanandpati <sradhanand.pati@seagate.com>

diff --git a/cli/src/factory_ops/boxing/init b/cli/src/factory_ops/boxing/init
--- a/cli/src/factory_ops/boxing/init
+++ b/cli/src/factory_ops/boxing/init
@@ -35,6 +35,42 @@ BASEDIR=$(dirname "${BASH_SOURCE}")
 . $BASEDIR/prov_tasks
 . $BASEDIR/shutdown
 
+
+serial_number=
+
+function usage {
+    echo "\
+    
+    Usage:
+        $0
+           [
+            -serial <Lyve Rack r1 serial number>
+           ]
+    Command Args:
+        -serial    <SERIAL_NUMBER>   Lyve Rack r1 serial number
+    "
+}
+
+function die {
+    echo >&2 "$@"
+    usage
+    exit 1
+}
+
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        -h|--help) usage; help; exit 0
+        ;;
+
+        -serial)
+            [ -z "$2" ] && die "Error: SERIAL NUMBER not provided";
+            serial_number="$2"
+            shift 2
+            ;;
+        *) echo "Invalid option $1"; usage; exit 1;;
+    esac
+done
+
 # Check if Boxing flag file is present
 box_flag_file="/opt/seagate/cortx/provisioner/generated_config/boxed"
 if [[ -f $box_flag_file ]]; then
@@ -42,6 +78,16 @@ if [[ -f $box_flag_file ]]; then
     create_unboxing_user
     exit 0
 fi
+
+if [[ ! -z $serial_number ]]; then
+    echo "WARNING: SERIAL NUMBER HAS NOT BEEN PROVIDED"
+else
+    salt "*" cmd.run "echo $serial_number > /opt/seagate/lr_serial_number"
+    salt "*" cmd.run "chmod 0644 /opt/seagate/lr_serial_number"
+    salt "*" cmd.run "chattr +i /opt/seagate/lr_serial_number"
+    echo "INFO: Lyve Rack r1 serial number can be found at /opt/seagate/lr_serial_number"
+fi
+    
 
 # Prepare shutdown
 ensure_healthy_cluster
