EOS-8353: Create special OS user for unboxing process

diff --git a/cli/src/factory_ops/boxing/init b/cli/src/factory_ops/boxing/init
--- a/cli/src/factory_ops/boxing/init
+++ b/cli/src/factory_ops/boxing/init
@@ -5,6 +5,13 @@ export LOG_FILE="${LOG_FILE:-/var/log/seagate/provisioner/boxing.log}"
 mkdir -p $(dirname "${LOG_FILE}")
 truncate -s 0 ${LOG_FILE}
 
+function trap_handler {
+    echo "***** ERROR! *****"
+    echo "For detailed error logs, please see: $LOG_FILE"
+    echo "******************"
+}
+trap trap_handler ERR
+
 BASEDIR=$(dirname "${BASH_SOURCE}")
 
 . $BASEDIR/prov_tasks
@@ -14,7 +21,7 @@ BASEDIR=$(dirname "${BASH_SOURCE}")
 # Shutdown HA
 if command -v pcs ; then
     echo "INFO: Starting maintenance mode..." 2>&1 | tee -a ${LOG_FILE}
-    hctl node maintenance --all 2>&1 | tee -a ${LOG_FILE}
+    hctl node maintenance --all --timeout-sec=600 2>&1 | tee -a ${LOG_FILE}
     echo "INFO: Initiating HA cluster stop..." 2>&1 | tee -a ${LOG_FILE}
     pcs cluster stop --all  2>&1 | tee -a ${LOG_FILE}
 else
@@ -25,6 +32,9 @@ fi
 stop_rabbitmq_cluster
 stop_services
 backup_files
+
+# Create user for unboxing
+create_unboxing_user
 
 # Create flag file
 boxing_flag
