EOS-8513: Print Lyve Drive Rack details at the end of boxing.

diff --git a/cli/src/factory_ops/boxing/prov_tasks b/cli/src/factory_ops/boxing/prov_tasks
--- a/cli/src/factory_ops/boxing/prov_tasks
+++ b/cli/src/factory_ops/boxing/prov_tasks
@@ -60,35 +60,101 @@ function backup_files {
 }
 
 function create_unboxing_user {
-    if ! command -v mkpasswd >/dev/null ; then
-        # Install required package if missing
-        yum install -y expect >/dev/null
+    set -euE
+    _create_date=$(date '+%Y-%m-%d')
+    _output_file="/root/Lyve_rack_SystemID_${_create_date}.txt"
+    _user="cortxub"
+    _sceret=
+
+    if [[ -f /opt/seagate/eos-prvsnr/generated_configs/cluster_id ]]; then
+        _secret=`cat /opt/seagate/eos-prvsnr/generated_configs/cluster_id | cut -d- -f 5`
+    else
+        echo "ERROR: Cortx cluster is not configured on this node" | tee -a ${LOG_FILE}
     fi
-    
-    SECRET=$(mkpasswd -l 10 -d 3 -c 3 -C 3 -s 0)
-    useradd --base-dir /tmp --inactive 2 --groups sys --shell /usr/bin/bash  --no-create-home --password $(openssl passwd -1 ${SECRET}) cortxub
-    passwd -e cortxub
-    
-    echo "**********************************************************" 2>&1 | tee -a ${LOG_FILE}
-    echo "NOTE: Store this information for unboxing."
-    echo "**********************************************************" 2>&1 | tee -a ${LOG_FILE}
-    
-    echo "System MAC: $(cat /sys/class/net/eno1/address)" 2>&1 | tee -a ${LOG_FILE}
-    echo "USERNAME:   cortxub" 2>&1 | tee -a ${LOG_FILE}
-    echo "PASSWORD:   ${SECRET}" 2>&1 | tee -a ${LOG_FILE}
- 
-    echo "**********************************************************" 2>&1 | tee -a ${LOG_FILE}
-    echo "NOTE: Password expires on first login." 2>&1 | tee -a ${LOG_FILE}
-    echo "**********************************************************" 2>&1 | tee -a ${LOG_FILE}
+
+    id $_user > /dev/null || {
+        echo "INFO: Creating user for first time login" | tee -a ${LOG_FILE}
+        useradd --base-dir /tmp --inactive 2 --groups sys --shell /usr/bin/bash  --no-create-home --password $(openssl passwd -1 ${_secret}) cortxub
+        passwd -e $_user
+    }
+
+    ###### Server A #####
+    echo -n "INFO: Getting serial numbers and mac addresses for server A.........." | tee -a ${LOG_FILE}
+    _serial_a=`dmidecode -t system | grep Serial | cut -d: -f 2`
+    _mac_bmc_a=`ipmitool lan print | grep "MAC Address" | awk '{ print $4 }'`
+    #_interface_mgmt_a=`ip -o link show | awk -F': ' '{print $2}' | grep eno1`
+    _interface_mgmt_a="eno1"
+    _mac_mgmt_a=`cat /sys/class/net/${_interface_mgmt_a}/address`
+    _interface_data_a=`ip -o link show | awk -F': ' '{print $2}' | grep enp | grep f0`
+    _mac_data_a=`cat /sys/class/net/${_interface_data_a}/address`
+    echo "Done" | tee -a ${LOG_FILE}
+
+    ###### Server B #####
+    echo -n "INFO: Getting serial numbers and mac addresses for server B.........." | tee -a ${LOG_FILE}
+    _serial_b=`ssh srvnode-2 "dmidecode -t system" | grep Serial | cut -d: -f 2`
+    _mac_bmc_b=`ssh srvnode-2 "ipmitool lan print" | grep 'MAC Address' | awk '{ print $4 }'`    
+    #_interface_mgmt_b=`ssh srvnode-2 "ip -o link show" | awk -F': ' '{print $2}' | grep eno1`
+    _interface_mgmt_b="eno1"
+    _mac_mgmt_b=`ssh srvnode-2 "cat /sys/class/net/${_interface_mgmt_b}/address"`
+    _interface_data_b=`ssh srvnode-2 "ip -o link show" | awk -F': ' '{print $2}' | grep enp | grep f0`
+    _mac_data_b=`ssh srvnode-2 "cat /sys/class/net/${_interface_data_b}/address"`
+    echo "Done" | tee -a ${LOG_FILE}
+
+    echo "\
+**************************************************
+NOTE: Store following information for unboxing.
+**************************************************" 2>&1 | tee -a ${LOG_FILE}
+
+    cat <<EOL > ${_output_file}
+**************************************************
+*             Lyve Drive Rack                    *
+**************************************************
+*         Lyve Drive Rack System ID              *
+*------------------------------------------------* 
+*                                                *
+*                                                *
+*                                                *
+**************************************************
+*    CORTX credentials for initial setup         *
+-------------------------------------------------*
+  user     : $_user
+  password : $_secret
+
+  NOTE: Password expires on first login.    
+
+**************************************************
+*                 Server A                       *
+*------------------------------------------------*
+  Serial Number            : $_serial_a           
+  Management Interface MAC : $_mac_mgmt_a
+  BMC Interface MAC        : $_mac_bmc_a
+  Data Interface MAC       : $_mac_data_a
+
+**************************************************
+*                 Server B                       *
+*------------------------------------------------*
+  Serial Number            : $_serial_b
+  Management Interface MAC : $_mac_mgmt_b
+  BMC Interface MAC        : $_mac_bmc_b
+  Data Interface MAC       : $_mac_data_b
+
+**************************************************
+EOL
+    cat ${_output_file} 2>&1 | tee -a ${LOG_FILE}
+
+    echo -e "\n\
+NOTE: The above system details are required for unboxing and is stored at: $_output_file
+      Please replace SystemID with actual System ID in the file name before shipping." | tee -a ${LOG_FILE}
 }
+
 
 function boxing_flag {
     #Flag file is created only on primary node,
     # as this helps to ensure unboxing is executed only on primary node.
     echo -n "INFO: Creating flag file on primary node....." | tee -a ${LOG_FILE}
 
-    local file_name="/opt/seagate/cortx/provisioner/generated_config/boxed"
-    
+    local file_name=${1:-/opt/seagate/cortx/provisioner/generated_config/boxed}
+
     if [ ! -f $file_name ]
     then
         timestamp=$(date "+%Y.%m.%d-%H.%M.%S")
