EOS-10336: root user can login via ssh (#397)
* EOS-10336:root user can login via ssh

Signed-off-by: sradhanand.pati <sradhanand.pati@seagate.com>

* Incorporating review comments

Signed-off-by: sradhanand.pati <sradhanand.pati@seagate.com>

* Permit root login from all private ips from cluster

Signed-off-by: sradhanand.pati <sradhanand.pati@seagate.com>

Co-authored-by: Pritam Bhavsar <pritam.bhavsar@seagate.com>
Co-authored-by: Andrey Kononykhin <andrey.kononykhin@seagate.com>
Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

diff --git a/cli/src/factory_ops/boxing/prov_tasks b/cli/src/factory_ops/boxing/prov_tasks
--- a/cli/src/factory_ops/boxing/prov_tasks
+++ b/cli/src/factory_ops/boxing/prov_tasks
@@ -79,6 +79,17 @@ function backup_files {
     echo "Done." | tee -a ${LOG_FILE}
 }
 
+function update_ssh_settings {
+    echo -n "INFO: Updating ssh settings on both nodes....." | tee -a ${LOG_FILE}
+
+    salt "*" state.apply components.system.config.sshd_boxing ${salt_opts} || (
+        echo "ERROR: Failed to update ssh settings from both nodes." | tee -a ${LOG_FILE}
+    )
+
+    echo "Done." | tee -a ${LOG_FILE}
+}
+
+
 function create_unboxing_user {
     set -euE
     _create_date=$(date '+%Y-%m-%d')
