Fix bugs found during testing.
Signed-off-by: Pritam Bhavsar <pritam.bhavsar@seagate.com>
Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

diff --git a/cli/src/factory_ops/boxing/prov_tasks b/cli/src/factory_ops/boxing/prov_tasks
--- a/cli/src/factory_ops/boxing/prov_tasks
+++ b/cli/src/factory_ops/boxing/prov_tasks
@@ -218,30 +218,47 @@ NOTE: The above system details are required for unboxing and is stored at: $_out
     done
 }
 
+function reset_vips {
+    #Remove VIPs for data and management network from Salt pillars
+
+    echo "Removing the VIPs from Salt configuration" | tee -a ${LOG_FILE}
+    echo "Removing Data VIP from cluster pillar" >> ${LOG_FILE}
+    provisioner pillar_set cluster/cluster_ip \"\" --logfile --logfile-filename ${LOG_FILE}
+    echo "Removing Management VIP from cluster pillar" >> ${LOG_FILE}
+    provisioner pillar_set cluster/mgmt_vip \"\" --logfile --logfile-filename ${LOG_FILE}
+    echo "Done" | tee -a ${LOG_FILE}
+
+}
 
 function reset_pub_data_ips {
     #Reset IPs for public data network
     #Update public data interface ips
-    if [[ -f "/var/lib/seagate/cortx/provisioner/shared/srv/pillar/groups/all/uu_cluster.sls" ]]; then
-        _cluster_sls_path=/var/lib/seagate/cortx/provisioner/shared/srv/pillar/groups/all/uu_cluster.sls
-    elif [[ -f "/srv/glusterfs/volume_prvsnr_data/srv/pillar/groups/all/uu_cluster.sls" ]]; then
-        _cluster_sls_path=/srv/glusterfs/volume_prvsnr_data/srv/pillar/groups/all/uu_cluster.sls
-    else
-        echo "ERROR: Cluster data is not updated correctly" >> ${LOG_FILE}
-        exit 1
-    fi
+    # if [[ -f "/var/lib/seagate/cortx/provisioner/shared/srv/pillar/groups/all/uu_cluster.sls" ]]; then
+    #     _cluster_sls_path=/var/lib/seagate/cortx/provisioner/shared/srv/pillar/groups/all/uu_cluster.sls
+    # elif [[ -f "/srv/glusterfs/volume_prvsnr_data/srv/pillar/groups/all/uu_cluster.sls" ]]; then
+    #     _cluster_sls_path=/srv/glusterfs/volume_prvsnr_data/srv/pillar/groups/all/uu_cluster.sls
+    # else
+    #     echo "ERROR: Cluster data is not updated correctly" >> ${LOG_FILE}
+    #     exit 1
+    # fi
 
-    echo "Removing the static IPs of public data network from pillar file for both servers" |tee -a ${LOG_FILE}
-    echo "Removing static data ip from $_cluster_sls_path for server A" >> $LOG_FILE
-    line_node1_ip=`grep -A8 -n "data_nw:"  $_cluster_sls_path | grep "public_ip_addr:" | cut -d- -f1 | head -1`
-    if [[ -n ${line_node1_ip} ]]; then
-        sed -ie "${line_node1_ip}s/.*/                public_ip_addr:/" $_cluster_sls_path
-    fi
-    echo "Removing static data ip from $_cluster_sls_path for server B" >> $LOG_FILE
-    line_node2_ip=`grep -A8 -n "data_nw:"  $_cluster_sls_path | grep "public_ip_addr:" | cut -d- -f1 | tail -1`
-    if [[ -n ${line_node2_ip} ]]; then
-        sed -ie "${line_node2_ip}s/.*/                public_ip_addr:/" $_cluster_sls_path
-    fi
+    # echo "Removing the static IPs of public data network from pillar file for both servers" |tee -a ${LOG_FILE}
+    # echo "Removing static data ip from $_cluster_sls_path for server A" >> $LOG_FILE
+    # line_node1_ip=`grep -A8 -n "data_nw:"  $_cluster_sls_path | grep "public_ip_addr:" | cut -d- -f1 | head -1`
+    # if [[ -n ${line_node1_ip} ]]; then
+    #     sed -ie "${line_node1_ip}s/.*/                public_ip_addr:/" $_cluster_sls_path
+    # fi
+    # echo "Removing static data ip from $_cluster_sls_path for server B" >> $LOG_FILE
+    # line_node2_ip=`grep -A8 -n "data_nw:"  $_cluster_sls_path | grep "public_ip_addr:" | cut -d- -f1 | tail -1`
+    # if [[ -n ${line_node2_ip} ]]; then
+    #     sed -ie "${line_node2_ip}s/.*/                public_ip_addr:/" $_cluster_sls_path
+    # fi
+
+    echo "Removing the IPs of public data network from Salt configuration" | tee -a ${LOG_FILE}
+    echo "Removing public data IP for Server A from cluster pillar" >> ${LOG_FILE}
+    provisioner pillar_set cluster/srvnode-1/network/data_nw/public_ip_addr \"\" --logfile --logfile-filename ${LOG_FILE}
+    echo "Removing public data IP for Server B from cluster pillar" >> ${LOG_FILE}
+    provisioner pillar_set cluster/srvnode-2/network/data_nw/public_ip_addr \"\" --logfile --logfile-filename ${LOG_FILE}
     echo "Done" | tee -a ${LOG_FILE}
 
     echo "INFO: Resetting the IPs of public data network interface on both nodes." | tee -a ${LOG_FILE}
@@ -255,7 +272,7 @@ function boxing_flag {
     # as this helps to ensure unboxing is executed only on primary node.
     echo -n "INFO: Creating flag file on primary node....." | tee -a ${LOG_FILE}
 
-    local file_name=${1:-/opt/seagate/cortx/provisioner/generated_config/boxed}
+    local file_name=${1:-/opt/seagate/cortx/provisioner/generated_configs/boxed}
 
     if [ ! -f $file_name ]
     then
diff --git a/cli/src/factory_ops/unboxing/init b/cli/src/factory_ops/unboxing/init
--- a/cli/src/factory_ops/unboxing/init
+++ b/cli/src/factory_ops/unboxing/init
@@ -244,100 +244,90 @@ salt '*' saltutil.refresh_grains ${salt_opts}
 sleep 2
 echo "Ok." | tee -a ${LOG_FILE}
 
-# After unboxing, the IP addresses in haproxy need to be updated
-echo -n "Updating new VIPs in haproxy configuration.................................." | tee -a ${LOG_FILE}
-salt "*" state.apply components.ha.haproxy.config ${salt_opts}
-sleep 2
-echo "Ok." | tee -a ${LOG_FILE}
 
-# TODO: Updating VIP in CSM HA needs mechanism to avoid repo creation in csm.prepare
-#echo -n "Updating Management VIP in CSM HA configuration file........................" | tee -a ${LOG_FILE}
-#salt "*" state.apply components.csm.ha.config ${salt_opts}
-#echo "Done." | tee -a ${LOG_FILE}
-
-if command -v pcs ; then
-    echo "Starting Cortx cluster" 2>&1 | tee -a ${LOG_FILE}
-    pcs cluster start --all 2>&1 | tee -a ${LOG_FILE}
-    echo "Done." | tee -a ${LOG_FILE}
-
-    echo "Starting Lyve Drive Rack services" 2>&1 | tee -a ${LOG_FILE}
-    sleep 5
-    hctl node unmaintenance --all 2>&1 | tee -a ${LOG_FILE}
-    echo "Done." | tee -a ${LOG_FILE}
-
-    if [[ ! -z "$static_data_ip_a" && ! -z "$static_data_ip_b" ]]; then
-        # Assign Static IPs on both the nodes
-        echo -n "Assigning static IPs to public data network................................." | tee -a ${LOG_FILE}
-        salt "*" state.apply components.system.network.data.direct ${salt_opts}
-        sleep 5     # Mindfulness break
-        echo "Ok." | tee -a ${LOG_FILE}
-    fi
-
-    # Update ClusterIP
-    echo -n "Configuring Data Network VIP................................................" | tee -a ${LOG_FILE}
-    salt "srvnode-1" state.apply components.ha.corosync-pacemaker.config.cluster_ip ${salt_opts}
-    sleep 5     # Mindfulness break
-    echo "Ok." | tee -a ${LOG_FILE}
-
-    echo -n "Updating new VIPs in haproxy configuration.................................." | tee -a ${LOG_FILE}
-    salt "*" state.apply components.ha.haproxy.config ${salt_opts}
-    sleep 5     # Mindfulness break
-    echo "Ok." | tee -a ${LOG_FILE}
-
-    # Update Management_vip
-
-    echo -n "Configuring Management Network VIP.........................................." | tee -a ${LOG_FILE}
-    salt "srvnode-1" state.apply components.ha.corosync-pacemaker.config.mgmt_vip ${salt_opts}
-    sleep 5     # Mindfulness break
-    echo "Ok." | tee -a ${LOG_FILE}
-
-    # Re-run Stonith
-    echo -n "Fencing the cluster with Stonith............................................" | tee -a ${LOG_FILE}
-    salt "srvnode-1" state.apply components.ha.corosync-pacemaker.config.stonith ${salt_opts}
-    sleep 5     # Mindfulness break...Breathe in...Breathe out
-    echo "Ok." | tee -a ${LOG_FILE}
-
-    echo "Thank you for your patience... Appreciate it!"
-
-else
+if ! command -v pcs ; then
     echo "[ERROR  ]: Command 'pcs' not found" 2>&1 | tee -a ${LOG_FILE}
     exit 1
 fi
 
-echo -n "Removing build URL from Salt configuration.................................." | tee -a ${LOG_FILE}
+echo "Starting Cortx cluster" 2>&1 | tee -a ${LOG_FILE}
+pcs cluster start --all 2>&1 | tee -a ${LOG_FILE}
+sleep 2
+
+echo "Starting Lyve Drive Rack services" 2>&1 | tee -a ${LOG_FILE}
+hctl node unmaintenance --all 2>&1 | tee -a ${LOG_FILE}
+sleep 5
+
+if [[ ! -z "$static_data_ip_a" && ! -z "$static_data_ip_b" ]]; then
+    # Assign Static IPs on both the nodes
+    echo -n "Assigning static IPs to public data network................................." | tee -a ${LOG_FILE}
+    salt "*" state.apply components.system.network.data.direct ${salt_opts}
+    sleep 5     # Mindfulness break
+    echo "Ok." | tee -a ${LOG_FILE}
+fi
+
+# Update ClusterIP
+echo -n "Configuring Data Network VIP................................................" | tee -a ${LOG_FILE}
+salt "srvnode-1" state.apply components.ha.corosync-pacemaker.config.cluster_ip ${salt_opts}
+sleep 5     # Mindfulness break
+echo "Ok." | tee -a ${LOG_FILE}
+
+echo -n "Updating new VIPs in haproxy configuration.................................." | tee -a ${LOG_FILE}
+salt "*" state.apply components.ha.haproxy.config ${salt_opts}
+sleep 5     # Mindfulness break
+echo "Ok." | tee -a ${LOG_FILE}
+
+# Update Management_vip
+
+echo -n "Configuring Management Network VIP.........................................." | tee -a ${LOG_FILE}
+salt "srvnode-1" state.apply components.ha.corosync-pacemaker.config.mgmt_vip ${salt_opts}
+sleep 5     # Mindfulness break
+echo "Ok." | tee -a ${LOG_FILE}
+
+# Re-run Stonith
+echo -n "Fencing the cluster with Stonith............................................" | tee -a ${LOG_FILE}
+salt "srvnode-1" state.apply components.ha.corosync-pacemaker.config.stonith ${salt_opts}
+sleep 5     # Mindfulness break...Breathe in...Breathe out
+echo "Ok." | tee -a ${LOG_FILE}
+
+echo -n "Updating Management VIP in CSM HA configuration file........................" | tee -a ${LOG_FILE}
+salt "*" state.apply components.csm.prepare ${salt_opts}
+echo "Ok." | tee -a ${LOG_FILE}
+
+echo "Removing build URL from Salt configuration" | tee -a ${LOG_FILE}
 provisioner pillar_set release/target_build \"\" --logfile --logfile-filename ${LOG_FILE}
 sleep 2
-echo "Ok." | tee -a ${LOG_FILE}
 
-echo -n "Removing stale URL (CentOS) from Salt configuration........................." | tee -a ${LOG_FILE}
+echo "Removing stale URL (CentOS) from Salt configuration" | tee -a ${LOG_FILE}
 provisioner pillar_set commons/cortx_commons/CentOS \"\" --logfile --logfile-filename ${LOG_FILE}
 sleep 2
-echo "Ok." | tee -a ${LOG_FILE}
 
-echo -n "Removing build URL (RedHat) from Salt configuration........................." | tee -a ${LOG_FILE}
+echo "Removing build URL (RedHat) from Salt configuration" | tee -a ${LOG_FILE}
 provisioner pillar_set commons/cortx_commons/RedHat \"\" --logfile --logfile-filename ${LOG_FILE}
 sleep 2
-echo "Ok." | tee -a ${LOG_FILE}
-
-echo -n "Removing Lustre URL (RedHat) from Salt configuration........................." | tee -a ${LOG_FILE}
-provisioner pillar_set commons/repo/lustre \"\" --logfile --logfile-filename ${LOG_FILE}
-sleep 2
-echo "Ok." | tee -a ${LOG_FILE}
-
-echo -n "Removing the repos with Seagate URL from Server A..........................." | tee -a ${LOG_FILE}
-seagate_refs_cleanup
-echo "Ok." | tee -a ${LOG_FILE}
 
 # Update SSPL init
 echo -n "Configuring Cortx RAS services on server A.................................." | tee -a ${LOG_FILE}
 salt "srvnode-2" state.apply components.sspl.config.commons ${salt_opts}; sleep 5
-sleep 2
 echo "Ok." | tee -a ${LOG_FILE}
 
 echo -n "Configuring Cortx RAS services on server B.................................." | tee -a ${LOG_FILE}
 salt "srvnode-1" state.apply components.sspl.config.commons ${salt_opts}; sleep 5
-sleep 2
 echo "Ok." | tee -a ${LOG_FILE}
+
+# echo -n "Configuring CSM services on Server B........................................" | tee -a ${LOG_FILE}
+# salt "srvnode-2" state.apply components.csm.config ${salt_opts}; sleep 5
+# echo "Ok." | tee -a ${LOG_FILE}
+
+# echo -n "Configuring CSM services on Server A........................................" | tee -a ${LOG_FILE}
+# salt "srvnode-1" state.apply components.csm.config ${salt_opts}; sleep 5
+# echo "Ok." | tee -a ${LOG_FILE}
+
+echo "Removing Lustre URL (RedHat) from Salt configuration" | tee -a ${LOG_FILE}
+provisioner pillar_set commons/repo/lustre \"\" --logfile --logfile-filename ${LOG_FILE}; sleep 2
+
+echo "Removing the repos with Seagate URL from Server A" | tee -a ${LOG_FILE}
+seagate_refs_cleanup
 
 echo "Restarting the cluster resources.........." | tee -a ${LOG_FILE}
 echo -n "ClusterIP.............................." | tee -a ${LOG_FILE}
@@ -362,6 +352,15 @@ pcs resource refresh uds >> ${LOG_FILE}
 sleep 5
 echo "Ok." | tee -a ${LOG_FILE}
 
+echo "Cleaning up resource history.............." | tee -a ${LOG_FILE}
+echo  -n "Cleaning stonith history.............." | tee -a ${LOG_FILE}
+pcs stonith history cleanup >> ${LOG_FILE}
+echo "Ok." | tee -a ${LOG_FILE}
+echo  -n "Cleaning failed resource history......" | tee -a ${LOG_FILE}
+pcs resource cleanup >> ${LOG_FILE}
+echo "Ok." | tee -a ${LOG_FILE}
+
+
 # lock unboxing user
 lock_unboxing_user
 
@@ -377,7 +376,7 @@ do
     fi
     echo -n "."
     try=$(( $try + 4 ))
-    sleep 4
+    sleep 2
 done
 echo -e "Ok.\n"
 
diff --git a/cli/src/factory_ops/unboxing/system_check b/cli/src/factory_ops/unboxing/system_check
--- a/cli/src/factory_ops/unboxing/system_check
+++ b/cli/src/factory_ops/unboxing/system_check
@@ -20,7 +20,7 @@
 
 # Functions in this file address following:
 #   1. Check boxing flag file and proceed only if boxing.<timestamp> file is present 
-#       /opt/seagate/cortx/provisioner/generated_config/boxing.<timestamp> 
+#       /opt/seagate/cortx/provisioner/generated_configs/boxing.<timestamp> 
 #   2. Check if IP is available on management network interface on node. Wait till one is obtained. 
 #   3. Check if hostname is available on node. Wait till one is obtained. 
 #   4. Ping across nodes over direct network to check connectivity and fetch peer hostname. Wait till success. 
@@ -40,14 +40,8 @@ BASEDIR=$(dirname "${BASH_SOURCE}")
 . ${BASEDIR}/../../common_utils/utility_scripts.sh
 
 export PRVSNR_ROOT="/opt/seagate/cortx/provisioner"
-if [[ -f "/var/lib/seagate/cortx/provisioner/shared/srv/pillar/groups/all/uu_cluster.sls" ]]; then
-    cluster_sls_path=/var/lib/seagate/cortx/provisioner/shared/srv/pillar/groups/all/uu_cluster.sls
-elif [[ -f "/srv/glusterfs/volume_prvsnr_data/srv/pillar/groups/all/uu_cluster.sls" ]]; then
-    cluster_sls_path= /srv/glusterfs/volume_prvsnr_data/srv/pillar/groups/all/uu_cluster.sls
-else
-    echo "ERROR: Cluster data is not updated correctly" >> ${LOG_FILE}
-    exit 1
-fi
+
+cluster_sls_path="${pillar_root}/uu_cluster.sls"
 
 function trap_handler {
     echo "***** ERROR! *****"
@@ -57,7 +51,7 @@ function trap_handler {
 trap trap_handler ERR
 
 function check_boxing_flag {
-    if [[ -f '/opt/seagate/cortx/provisioner/generated_config/boxed' ]]
+    if [[ -f '/opt/seagate/cortx/provisioner/generated_configs/boxed' ]]
     then
         echo "DEBUG: Boxed file found." >> ${LOG_FILE}
     else
@@ -80,13 +74,8 @@ function check_salt_services {
         systemctl start salt-minion
     fi
 
-    # Check salt-minion on secondary node.
-    local node_2_private_data_ip=$(grep -m2 -A8 -P "data_nw:" ${cluster_sls_path}|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
-    if [[ -z ${node_2_private_data_ip} ]]; then
-        node_2_private_data_ip=${pvt_ip_b}
-    fi
-    if ! (ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${node_2_private_data_ip} "systemctl status salt-master>/dev/null"); then
-        ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${node_2_private_data_ip} "systemctl start salt-minion"
+    if ! ($ssh_cmd ${pvt_ip_b} "systemctl status salt-master>/dev/null"); then
+        $ssh_cmd ${pvt_ip_b} "systemctl start salt-minion"
     fi
 }
 
@@ -100,8 +89,8 @@ function check_hostname {
 
 function check_pvt_data_connectivity {
     local private_data_if=$(grep -m1 -A5 -P "data_nw:" ${cluster_sls_path}|grep -A2 "iface:"|tail -1|cut -d'-' -f2|tr -d "[:space:]")
-    echo "      Private n/w IP (Server A)     : $pvt_ip_a" | tee -a ${LOG_FILE}
-    echo "      Private n/w IP (Server B)     : $pvt_ip_b" | tee -a ${LOG_FILE}
+    echo "      Private n/w IP (Server A): $pvt_ip_a" | tee -a ${LOG_FILE}
+    echo "      Private n/w IP (Server B): $pvt_ip_b" | tee -a ${LOG_FILE}
     echo -n "Checking connectivity from server A to server B over private network........" | tee -a ${LOG_FILE}
     # node1 => node2: private data interface
     ping -c1 -W2 -I${private_data_if} ${pvt_ip_b} > /dev/null || (echo "ERROR: Unable to ping srvnode-2 from srvnode-1, over ${private_data_if}" |tee -a ${LOG_FILE}; exit 1)
@@ -109,7 +98,7 @@ function check_pvt_data_connectivity {
 
     echo -n "Checking connectivity from server B to server A over private network........" | tee -a ${LOG_FILE}
     # node2 => node1: private data interface
-    ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "ping -c1 -W2 -I${private_data_if} ${pvt_ip_b}" > /dev/null || (echo "ERROR: Unable to ping srvnode-1 from srvnode-2, over ${private_data_if}" |tee -a ${LOG_FILE}; exit 1)
+    ssh -i /root/.ssh/id_rsa_prvsnr -o ConnectTimeout=5 -o "StrictHostKeyChecking no" ${pvt_ip_b} "ping -c1 -W2 -I${private_data_if} ${pvt_ip_a}" > /dev/null || (echo "ERROR: Unable to ping srvnode-1 from srvnode-2, over ${private_data_if}" |tee -a ${LOG_FILE}; exit 1)
     echo "Ok." | tee -a ${LOG_FILE}
 }
 
@@ -127,21 +116,15 @@ function check_mgmt_ip {
         fi
     fi
     
-    # local public_data_if=$(grep -m1 -A3 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|tail -1|cut -d'-' -f2|tr -d "[:space:]")
-    # local private_data_if=$(grep -m1 -A4 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|tail -1|cut -d'-' -f2|tr -d "[:space:]")
-
     # Node-1 IPs
     # ip for mgmt interface
     local mgmt_ip_1=$((ip addr show dev ${mgmt_if}|grep inet|grep -v inet6|grep -Po "\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}" || echo "ERROR: IP address missing for ${mgmt_if} on srvnode-1" || (tee -a ${LOG_FILE}; exit 1))|head -1)
     echo "      Management IP (Server A) : ${mgmt_ip_1}" | tee -a ${LOG_FILE}
-    
-    # ip for public data interface
-    # local public_data_ip_1=$(ip addr show dev ${public_data_if}|grep inet|grep -v inet6|grep -Po "\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}"|head -1)
-    # echo ${public_data_ip_1}
+
 
     # Node-2 IPs
     # ip for mgmt interface
-    local mgmt_ip_2=$((ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "ip addr show dev ${mgmt_if}|grep inet|grep -v inet6|grep -Po \"\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\"" || (echo "ERROR: IP address missing for ${mgmt_if} on srvnode-2" | tee -a ${LOG_FILE}; echo 1))|head -1)
+    local mgmt_ip_2=$(($ssh_cmd ${pvt_ip_b} "ip addr show dev ${mgmt_if}|grep inet|grep -v inet6|grep -Po \"\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\"" || (echo "ERROR: IP address missing for ${mgmt_if} on srvnode-2" | tee -a ${LOG_FILE}; echo 1))|head -1)
     echo "      Management IP (Server B) : ${mgmt_ip_2}" | tee -a ${LOG_FILE}
 
     # ip for public data interface
@@ -157,7 +140,7 @@ function check_mgmt_ip {
 
     # node2 => node1: private data interface
     echo -n "Checking connectivity from server B to server A over management network....." | tee -a ${LOG_FILE}
-    ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "ping -c1 -W2 -I${mgmt_if} ${mgmt_ip_1}" > /dev/null || (echo "ERROR: Unable to ping srvnode-1 from srvnode-2, over ${mgmt_if}" |tee -a ${LOG_FILE}; exit 1)
+    ssh -i /root/.ssh/id_rsa_prvsnr -o ConnectTimeout=5 -o "StrictHostKeyChecking no" ${pvt_ip_b} "ping -c1 -W2 -I${mgmt_if} ${mgmt_ip_1}" > /dev/null || (echo "ERROR: Unable to ping srvnode-1 from srvnode-2, over ${mgmt_if}" |tee -a ${LOG_FILE}; exit 1)
     echo "Ok." | tee -a ${LOG_FILE}
 }
 
