EOS-26179: added validations for image versions in upgrade scenario
Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

diff --git a/src/setup/cortx_deploy b/src/setup/cortx_deploy
--- a/src/setup/cortx_deploy
+++ b/src/setup/cortx_deploy
@@ -58,6 +58,7 @@ function conf_get {
 DEBUG_FLAG=false
 SOLUTION_CONFIG="/etc/cortx/solution"
 CORTX_CONFSTORE="yaml:///etc/cortx/cluster.conf"
+RELEASE_INFO="yaml:///opt/seagate/cortx/RELEASE.INFO"
 
 while [ $# -gt 0 ];  do
     case $1 in
@@ -110,6 +111,46 @@ node_id=`cat /etc/machine-id`
 cluster_id=$(conf_get $(yaml_config $CLUSTER_INFO) "cluster>id")
 log $INFO "Starting provisioning on node $node_id which is part of cluster $cluster_id."
 
+deploy=false
+upgrade=false
+# Check current image version
+CONFSTOR_FILE=$(awk -F:// '{print $2}' <<< $CORTX_CONFSTORE)
+# check if confstore file is empty or not present
+if [ ! -s "$CONFSTOR_FILE" ]; then
+    log $INFO "$CORTX_CONFSTORE file not found or file is empty"
+    log $INFO "deployment set to true"
+    deployment=true
+else
+    current_full_ver=$(conf_get $CORTX_CONFSTORE "cortx>common>release>version")
+    # if current version is not available in confstore
+    if [ $current_full_ver = "[null]" ]; then
+        deployment=true
+    else
+        # Below can be used when subversioning is considered.
+        #current_primary_ver=$(awk -F. '{print $1 "." $2 "." $3}' <<< $current_full_ver)
+        current_ver=$(awk -F. '{print $4}' <<< $current_full_ver)
+    fi
+fi
+
+image_full_ver=$(sed -e 's/[][]//g' -e 's/"//g' <<< $(conf_get $RELEASE_INFO "VERSION"))
+# Below can be used when subversioning is considered.
+#image_primary_ver=$(awk -F- '{print $1}' <<<  $image_full_ver )
+image_ver=$(awk -F- '{print $2}' <<<  $image_full_ver)
+
+if [ $current_ver -eq $image_ver ]; then
+    if [ ! -z $FORCE_PROVISIONING ]; then
+        deploy=true
+    else
+        return 0
+    fi
+elif [ $current_ver -gt $image_ver ]; then
+    log $ERROR " Current version:$current_full_ver of cortx-all is greater than input image version:$image_full_ver"
+    exit 1
+else
+    deploy=false
+    upgrade=true
+fi
+
 # Apply Cluster Config
 log $INFO "cortx_setup config apply -f $(yaml_config $CLUSTER_INFO) -c '$CORTX_CONFSTORE' $FORCE_PROVISIONING"
 cortx_setup config apply -f $(yaml_config $CLUSTER_INFO) -c "$CORTX_CONFSTORE" $FORCE_PROVISIONING;
@@ -127,9 +168,14 @@ then
     cortx_setup config validate -f $(yaml_config $CONFIG_INFO) -c "$CORTX_CONFSTORE" || exit 1
 fi
 
-# Bootstrap Cluster
-log $INFO "cortx_setup cluster bootstrap -c '$CORTX_CONFSTORE' $FORCE_PROVISIONING"
-cortx_setup cluster bootstrap -c "$CORTX_CONFSTORE" $FORCE_PROVISIONING;
+if [[ $deploy = true && $upgrade = false ]]; then
+    # Bootstrap Cluster
+    log $INFO "cortx_setup cluster bootstrap -c '$CORTX_CONFSTORE' $FORCE_PROVISIONING"
+    cortx_setup cluster bootstrap -c "$CORTX_CONFSTORE" $FORCE_PROVISIONING;
+elif [[ $deploy = false && $upgrade = true ]]; then
+    log $INFO "cortx_setup cluster upgrade -c '$CORTX_CONFSTORE' $FORCE_PROVISIONING"
+    cortx_setup cluster upgrade -c "$CORTX_CONFSTORE" $FORCE_PROVISIONING;
+fi
 
 # Check if debugging is enabled
 if [ $DEBUG_FLAG = true ]; then
