EOS-27087: Improve version compatibility check.
Signed-off-by: Shriya Deshmukh <shriya.deshmukh@seagate.com>

diff --git a/src/setup/cortx_deploy b/src/setup/cortx_deploy
--- a/src/setup/cortx_deploy
+++ b/src/setup/cortx_deploy
@@ -138,26 +138,21 @@ log $INFO "Starting provisioning on node $node_id."
 
 # Check current image version
 installed_version=$(conf_get $CORTX_CONFSTORE "node>$node_id>provisioning>version")
-# if current version is not available in confstore
-[[ $installed_version != "null" ]] && current_version=$(awk -F- '{print $2}' <<< $installed_version)
-
 release_version=$(conf_get $RELEASE_INFO "VERSION")
-# Below can be used when subversioning is considered.
-#update_prim_version=$(awk -F- '{print $1}' <<<  $release_version )
-image_version=$(awk -F- '{print $2}' <<<  $release_version)
 
-#  [[ $image_version != '0' ]] Is a temprory patch for community deployment for build number 0 condition and 
-#   needs to be removed as part of [EOS-27087]
-[[ $current_version -eq $image_version && -z $FORCE_PROVISIONING ]] && [[ $image_version != '0' ]] &&
-    log $INFO "current_version ($installed_version) = image_version ($release_version)" &&
-    exit 0
-[[ $current_version -gt $image_version ]] &&
-    log $ERROR "Invalid image. current_version ($installed_version) > image_version ($release_version)" &&
-    exit 1
+if [ $installed_version == "null" ]
+then
+    action="deploy"
+else
+    [[ $installed_version == $release_version && -z $FORCE_PROVISIONING ]] &&
+        log $INFO "installed_version ($installed_version) = release_version ($release_version)" &&
+        exit 0
+    [[ $installed_version > $release_version ]] &&
+        log $ERROR "Invalid image. installed_version ($installed_version) > release_version ($release_version)" &&
+        exit 1
 
-action="deploy"
-
-[[ ! -z $current_version ]] && [[ $current_version -lt $image_version ]] && action="upgrade"
+    [[ ! -z $installed_version ]] && [[ $installed_version < $release_version ]] && action="upgrade"
+fi
 
 case $action in
     deploy)
@@ -171,7 +166,7 @@ case $action in
         upgrade
         ;;
     *)
-        log $ERROR "Internal error. Could not determine version. Invalid image. current_version is ($installed_version) and image_version is ($release_version)"
+        log $ERROR "Internal error. Could not determine version. Invalid image. current_version is ($installed_version) and release_version is ($release_version)"
         ;;
 esac
 # Check if debugging is enabled
