EOS-27087: Improve version compatibility check. (#6318)
* EOS-27087: Improve version compatibility check.

Signed-off-by: Shriya Deshmukh <shriya.deshmukh@seagate.com>

* Add version_comparison in deploy script.

Signed-off-by: Shriya Deshmukh <shriya.deshmukh@seagate.com>

* Addressed review comments.

Signed-off-by: Shriya Deshmukh <shriya.deshmukh@seagate.com>

diff --git a/src/setup/cortx_deploy b/src/setup/cortx_deploy
--- a/src/setup/cortx_deploy
+++ b/src/setup/cortx_deploy
@@ -35,7 +35,7 @@ function show_usage {
     exit 1
 }
 
-function yaml_config {
+function make_url {
     local config=$1
     echo "yaml://$config"
 }
@@ -50,11 +50,11 @@ function conf_get {
 function apply_config {
     for file in "$SOLUTION_CONFIG"/*
     do
-        if [ -f "$file" ]
+        [[ ! -f "$file" ]] && return
+        if [[ "$(conf_get $(make_url $file) 'cluster')" != "null" || "$(conf_get $(make_url $file) 'cortx')" != "null" ]]
         then
-            [[ "$(conf_get $(yaml_config $file) 'cluster')" != "null" || "$(conf_get $(yaml_config $file) 'cortx')" != "null" ]] &&
-            log $INFO "cortx_setup config apply -f $(yaml_config $file) -c '$CORTX_CONFSTORE' $FORCE_PROVISIONING"
-            cortx_setup config apply -f $(yaml_config $file) -c "$CORTX_CONFSTORE" $FORCE_PROVISIONING;
+            log $INFO "cortx_setup config apply -f $(make_url $file) -c '$CORTX_CONFSTORE' $FORCE_PROVISIONING"
+            cortx_setup config apply -f $(make_url $file) -c "$CORTX_CONFSTORE" $FORCE_PROVISIONING;
         fi
     done
 }
@@ -75,13 +75,39 @@ function validate_config {
     for file in "$SOLUTION_CONFIG"/*
     do
         # Validate config
-        if [ -f "$file" ]
+        [[ ! -f "$file" ]] && return
+        if [[ "$(conf_get $(make_url $file) 'cluster')" != "null" || "$(conf_get $(make_url $file) 'cortx')" != "null" ]]
         then
-            [[ "$(conf_get $(yaml_config $file) 'cluster')" != "null" || "$(conf_get $(yaml_config $file) 'cortx')" != "null" ]] &&
-            log $INFO "cortx_setup config validate -f $(yaml_config $file) -c '$CORTX_CONFSTORE'"
-            cortx_setup config validate -f $(yaml_config $file) -c "$CORTX_CONFSTORE" || return 1
+            log $INFO "cortx_setup config validate -f $(make_url $file) -c '$CORTX_CONFSTORE'"
+            cortx_setup config validate -f $(make_url $file) -c "$CORTX_CONFSTORE" || return 1
         fi
     done
+}
+
+function compare {
+    # Returns
+    # -1 if $1 < v2
+    # 0 if $1 == $2
+    # 1 if $1 > $2
+    deploy_ver_spec=${1%-[0-9]*}
+    release_ver_spec=${2%-[0-9]*}
+
+    deploy_ver=${deploy_ver_spec%.[0-9]}
+    release_ver=${release_ver_spec%.[0-9]}
+    [[ $deploy_ver < $release_ver ]] && echo "-1" && return
+    [[ $deploy_ver > $release_ver ]] && echo "1" && return
+
+    deploy_ver=${deploy_ver_spec#[0-9].[0-9].}
+    release_ver=${release_ver_spec#[0-9].[0-9].}
+    [[ $deploy_ver -lt $release_ver ]] && echo "-1" && return
+    [[ $deploy_ver -gt $release_ver ]] && echo "1" && return
+
+    deploy_build=${1#[0-9.]*-}
+    release_build=${2#[0-9.]*-}
+    [[ $deploy_build -lt $release_build ]] && echo "-1" && return
+    [[ $deploy_build -gt $release_build ]] && echo "1" && return
+
+    echo "0"
 }
 
 # Constants
@@ -138,26 +164,22 @@ log $INFO "Starting provisioning on node $node_id."
 
 # Check current image version
 installed_version=$(conf_get $CORTX_CONFSTORE "node>$node_id>provisioning>version")
-# if current version is not available in confstore
-[[ $installed_version != "null" ]] && current_version=$(awk -F- '{print $2}' <<< $installed_version)
-
 release_version=$(conf_get $RELEASE_INFO "VERSION")
-# Below can be used when subversioning is considered.
-#update_prim_version=$(awk -F- '{print $1}' <<<  $release_version )
-image_version=$(awk -F- '{print $2}' <<<  $release_version)
 
-#  [[ $image_version != '0' ]] Is a temprory patch for community deployment for build number 0 condition and 
-#   needs to be removed as part of [EOS-27087]
-[[ $current_version -eq $image_version && -z $FORCE_PROVISIONING ]] && [[ $image_version != '0' ]] &&
-    log $INFO "current_version ($installed_version) = image_version ($release_version)" &&
-    exit 0
-[[ $current_version -gt $image_version ]] &&
-    log $ERROR "Invalid image. current_version ($installed_version) > image_version ($release_version)" &&
-    exit 1
+if [ $installed_version == "null" ]
+then
+    action="deploy"
+else
+    ret_code=$(compare $installed_version $release_version)
+    [[ "$ret_code" == "0" && -z $FORCE_PROVISIONING ]] &&
+        log $INFO "installed_version ($installed_version) = release_version ($release_version)" &&
+        exit 0
+    [[ "$ret_code" == "1" ]] &&
+        log $ERROR "Invalid image. installed_version ($installed_version) > release_version ($release_version)" &&
+        exit 1
 
-action="deploy"
-
-[[ ! -z $current_version ]] && [[ $current_version -lt $image_version ]] && action="upgrade"
+    [[ ! -z $installed_version ]] && [[ "$ret_code" == "-1" ]] && action="upgrade"
+fi
 
 case $action in
     deploy)
@@ -171,7 +193,7 @@ case $action in
         upgrade
         ;;
     *)
-        log $ERROR "Internal error. Could not determine version. Invalid image. current_version is ($installed_version) and image_version is ($release_version)"
+        log $ERROR "Internal error. Could not determine version. Invalid image. current_version is ($installed_version) and release_version is ($release_version)"
         ;;
 esac
 # Check if debugging is enabled
