Updates for 3-node deployment and destroy (#1057)
* Updates for 3-node deployment and destroy

Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

* Rename Jenkinsfile and updated 3node destroy

Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

* Fix the disk entries in config.ini

Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

* Modified to support node with 8-attached disks

Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

* Dynamic disk allocation in config.ini

Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

* Review comments addressed

Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

diff --git a/devops/ci/single_node_deploy/destroy.jenkinsfile b/devops/ci/single_node_deploy/destroy.jenkinsfile
--- a/devops/ci/single_node_deploy/destroy.jenkinsfile
+++ b/devops/ci/single_node_deploy/destroy.jenkinsfile
@@ -19,54 +19,33 @@ node {
     properties([
         buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '5', numToKeepStr: '5')),
         parameters([
-            string(defaultValue: '', description: 'FQDN of first VM to destroy.', name: 'HOST_NAME_1', trim: true),
-            string(defaultValue: '', description: 'FQDN of second VM to destroy.', name: 'HOST_NAME_2', trim: true),
-            string(defaultValue: '', description: 'FQDN of third VM to destroy.', name: 'HOST_NAME_3', trim: true),
+            string(defaultValue: '', description: 'FQDN of VM to destroy on.', name: 'HOST_NAME', trim: true),
             password(description: 'root user password for the target node.', name: 'PASSWORD')
         ])
     ])
     
-    def remotes = []
-    
-    def remote_node = [:]
-    remote_node.name = "srvnode-1"
-    remote_node.host = HOST_NAME_1
-    remote_node.user = 'root'
-    remote_node.password = PASSWORD
-    remote_node.allowAnyHosts = true
-    remotes[0] = remote_node
-    
-    remote_node = [:]
-    remote_node.name = "srvnode-2"
-    remote_node.host = HOST_NAME_2
-    remote_node.user = 'root'
-    remote_node.password = PASSWORD
-    remote_node.allowAnyHosts = true
-    remotes[1] = remote_node
-    
-    remote_node = [:]
-    remote_node.name = "srvnode-3"
-    remote_node.host = HOST_NAME_3
-    remote_node.user = 'root'
-    remote_node.password = PASSWORD
-    remote_node.allowAnyHosts = true
-    remotes[2] = remote_node
-
-    ansiColor('xterm') {
-        for ( remote in remotes.reverse() ) {
-            stage("${remote.name}: SSH Connectivity Check") {
+    def remote = [:]
+    withEnv(["SSHPASS=${PASSWORD}"]) {
+        ansiColor('xterm') {
+            remote.name = "srvnode-1"
+            remote.host = HOST_NAME
+            remote.user = 'root'
+            remote.password = PASSWORD
+            remote.allowAnyHosts = true
+            stage("SSH Connectivity Check") {
+                if (PASSWORD.isEmpty()) {
+                    error "Target VM password cannot be empty."
+                }
                 sshCommand remote: remote, command: "exit"
-                echo "Successfully connected to VM ${remote.host}!"
+                echo "Successfully connected to VM ${HOST_NAME}!"
             }
-
-            stage("${remote.name}: Teardown of Cortx Stack!") {
+            stage("Teardown of Cortx Stack!") {
                 sshCommand remote: remote, command: """
-                    /opt/seagate/cortx/provisioner/cli/destroy-vm --ctrlpath-states --iopath-states --prereq-states --system-states || true
+                    /opt/seagate/cortx/provisioner/cli/destroy-vm --ctrlpath-states --iopath-states --prereq-states --system-states --ha-states || true
                 """
                 echo "Successfully teardown of Cortx Stack!"
             }
-
-            stage("${remote.name}: Stop Salt services") {
+            stage("Stop services") {
                 sshCommand remote: remote, command: """
                     systemctl status glustersharedstorage >/dev/null && systemctl stop glustersharedstorage || true
                     systemctl status glusterfsd >/dev/null && systemctl stop glusterfsd || true
@@ -76,15 +55,16 @@ node {
                 """
                 echo "Sucessfully stopped salt and gluster services"
             }
-
-            stage("${remote.name}: Uninstall rpms") {
+            stage("Uninstall rpms") {
                 sshCommand remote: remote, command: """
                     yum erase -y cortx-prvsnr cortx-prvsnr-cli      # Cortx Provisioner packages
                     yum erase -y gluster-fuse gluster-server        # Gluster FS packages
                     yum erase -y salt-minion salt-master salt-api   # Salt packages
                     yum erase -y python36-m2crypto                  # Salt dependency
                     yum erase -y python36-cortx-prvsnr              # Cortx Provisioner API packages
+                    # Brute clean for any cortx rpm packages
                     yum erase -y *cortx*
+                    # Re-condition yum db
                     yum autoremove -y
                     yum clean all
                     rm -rf /var/cache/yum
@@ -98,28 +78,30 @@ node {
                 """
                 echo "Successfully uninstalled rpms"
             }
-
-            stage("${remote.name}: Cleanup bricks and other directories") {
+            stage("Cleanup bricks and other directories") {
                 sshCommand remote: remote, command: """
                     # Cortx software dirs
                     rm -rf /opt/seagate/cortx
                     rm -rf /opt/seagate/cortx_configs
                     rm -rf /opt/seagate
                     # Bricks cleanup
-                    test -e /var/lib/seagate && rm -rf /var/lib/seagate
-                    test -e /srv/glusterfs && rm -rf /srv/glusterfs
+                    test -e /var/lib/seagate && rm -rf /var/lib/seagate || true
+                    test -e /srv/glusterfs && rm -rf /srv/glusterfs || true
                     # Cleanup Salt
-                    test -e /var/cache/salt && rm -rf /var/cache/salt
-                    test -e /etc/salt && rm -rf /etc/salt
+                    test -e /var/cache/salt && rm -rf /var/cache/salt || true
+                    test -e /etc/salt && rm -rf /etc/salt || true
                     # Cleanup Provisioner profile directory
-                    test -e /opt/isos && rm -rf /opt/isos
-                    test -e /root/.provisioner && rm -rf /root/.provisioner
-                    test -e /etc/yum.repos.d/RELEASE_FACTORY.INFO && rm -f /etc/yum.repos.d/RELEASE_FACTORY.INFO
-                    test -e /root/.ssh && rm -rf /root/.ssh
+                    test -e /opt/isos && rm -rf /opt/isos || true
+                    test -e /root/.provisioner && rm -rf /root/.provisioner || true
+                    test -e /etc/yum.repos.d/RELEASE_FACTORY.INFO && rm -f /etc/yum.repos.d/RELEASE_FACTORY.INFO || true
+                    test -e /root/.ssh && rm -rf /root/.ssh || true
                 """
                 echo "Successfully removed!"
             }
         }
+
+        // sh label: '', script: "mkdir -p archives/provisioner_cluster.json"
+        // archiveArtifacts artifacts: '/opt/seagate/cortx_configs/provisioner_cluster.json,/var/log/seagate/provisioner/setup.log', followSymlinks: false
     }
-    // archiveArtifacts artifacts: '/opt/seagate/cortx_configs/provisioner_cluster.json,/var/log/seagate/provisioner/setup.log', followSymlinks: false
 }
+
