updates debug related code
Signed-off-by: Andrey Kononykhin <andrey.kononykhin@seagate.com>

diff --git a/devops/ci/Jenkinsfile.ci b/devops/ci/Jenkinsfile.ci
--- a/devops/ci/Jenkinsfile.ci
+++ b/devops/ci/Jenkinsfile.ci
@@ -1,13 +1,44 @@
 #!/usr/bin/env groovy
 
 def err = null
+def branchName = env.ghprbSourceBranch ?: env.BRANCH_NAME ?: env.sha1 ?: 'nobranch'
+branchName = branchName.replace('/','_')
+
+dockerImage = "seagate/cortx-prvsnr:ci-${branchName}"
 
 Map config = [
     staticValidation: true,
     dynamicValidation: true,
     sendNotif: true,
-    nodeLabel: 'centos-prvsnr-node'
+    nodeLabel: 'cortx-prvsnr-ci',
+    testMarkers: 'unit'
 ]
+
+def getMarkers(String str) {
+    def pattern = /.*test (.+) please/
+    def matcher = (str =~ pattern)
+    return !!matcher ? matcher[0][1] : null
+}
+
+if (env.ghprbCommentBody) {
+    config.testMarkers = getMarkers(env.ghprbCommentBody)
+
+    if (!config.testMarkers) {
+       throw new Exception("GitHub comment lacks markers: $env.ghprbCommentBody")
+    }
+} else {
+    def test_markers = []
+
+    if(env.topic) {
+        test_markers.add(env.topic)
+    }
+
+    if(env.level) {
+        test_markers.add(env.level)
+    }
+
+    config.testMarkers = test_markers.join(' and ')
+}
 
 
 def nodeWrapper(label=null, body) {
@@ -17,11 +48,30 @@ def nodeWrapper(label=null, body) {
             body()
         } finally {
             echo "Cleanup"
+            cleanDocker()
             cleanWs()
         }
     }
 }
 
+def buildDocker(imageName, dockerfile, ctx, add_args='') {
+    return docker.build("$imageName", "$add_args -f $dockerfile $ctx")
+}
+
+def buildUnitDocker() {
+    def uid = sh(returnStdout: true, script: 'id -u').trim()
+    def gid = sh(returnStdout: true, script: 'id -g').trim()
+    return buildDocker(
+        dockerImage,
+        "devops/ci/Dockerfile.unit",
+        "api",
+        "--build-arg uid=$uid --build-arg gid=$gid"
+    )
+}
+
+def cleanDocker(){
+    sh("docker rmi -f ${dockerImage} || true")
+}
 
 Closure preparePythonEnv = {
     String testPipenvReport = "pipenv.out"
@@ -43,6 +93,33 @@ Closure staticValidation = {
 
     checkout scm
 
+    def dockerImage = null
+
+    stage('Build docker image') {
+        dockerImage = buildUnitDocker()
+    }
+
+    dockerImage.inside {
+        // preparePythonEnv()
+
+        String testPythonReport = "flake8.out.txt"  // TODO not configurable for now
+        stage('Check python') {
+            // TODO check other python sources (not only 'test')
+            try {
+                sh "bash -x devops/ci/validate_python.sh"
+            } catch (_err) {
+                archiveArtifacts artifacts: testPythonReport, allowEmptyArchive: true
+                echo "Python static validation failed: $_err"
+                // throw _err
+            }
+        }
+    }
+
+    return
+
+
+
+    /*
     preparePythonEnv()
 
     String testPythonReport = "flake8.out"  // TODO not configurable for now
@@ -59,6 +136,7 @@ Closure staticValidation = {
             // throw _err
         }
     }
+    */
 
     String testYamlReport = "yamllint.out"  // TODO not configurable for now
     stage('Check yaml') {
@@ -87,8 +165,10 @@ Closure dynamicValidation = {
     String testReportFileNamePlain = "pytest.out.txt"
     String pytestArgs = "-l -vv --junit-xml=$testReportFileNameXml --env-provider docker"
     String pytestTargets = ""
-    String pytestMarkers = "not cortx_bvt"
+    // FIXME debug
+    String pytestMarkers = "(${config.testMarkers}) and debug"
 
+    /*
     try {
         stage('Clean VirtualBox environment') {
             sh "bash -x devops/ci/clean_vbox.sh vms"
@@ -102,6 +182,23 @@ Closure dynamicValidation = {
             stage('Run tests') {
                 sh """
                     pipenv run bash -x devops/ci/run_tests.sh "$pytestArgs $pytestTargets" "$pytestMarkers" "$testReportFileNamePlain"
+                """
+            }
+        }
+    */
+
+    def dockerImage = null
+
+    stage('Build docker image') {
+        dockerImage = buildUnitDocker()
+    }
+
+    try {
+        dockerImage.inside {
+            // run tests
+            stage('Run tests') {
+                sh """
+                    bash -x devops/ci/run_tests.sh "$pytestArgs $pytestTargets" "$pytestMarkers" "$testReportFileNamePlain"
                 """
             }
         }
@@ -164,15 +261,14 @@ try {
 
     stage('Notification') {
         if (config.sendNotif) {
-            /* TBD
             def emailMessage = [
-                body: '$DEFAULT_CONTENT',
+                body: '${JELLY_SCRIPT,template="html"}',
                 replyTo: '$DEFAULT_REPLYTO',
                 subject: '$DEFAULT_SUBJECT',
-                recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']]
+                recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
+                to: '$DEFAULT_RECIPIENTS',
             ]
             emailext emailMessage
-            */
         }
     }
 }
