EOS-14289: Unboxing changes, ported fro Beta.
Signed-off-by: Pritam Bhavsar <pritam.bhavsar@seagate.com>

diff --git a/cli/src/factory_ops/unboxing/config_update b/cli/src/factory_ops/unboxing/config_update
--- a/cli/src/factory_ops/unboxing/config_update
+++ b/cli/src/factory_ops/unboxing/config_update
@@ -38,11 +38,6 @@ BASEDIR=$(dirname "${BASH_SOURCE}")
 PRVSNR_ROOT="/opt/seagate/cortx/provisioner"
 salt_opts="--no-color --out-file=${LOG_FILE} --out-file-append"
 
-# private_data_ip_node_1=$(grep -m1 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
-# private_data_ip_node_2=$(grep -m2 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
-#private_data_ip_node_1=$(get_pillar_data cluster:srvnode-1:network:data_nw:pvt_ip_addr)
-#private_data_ip_node_2=$(get_pillar_data cluster:srvnode-2:network:data_nw:pvt_ip_addr)
-
 function trap_handler {
     echo "***** ERROR! *****"
     echo "For detailed error logs, please see: $LOG_FILE"
@@ -63,9 +58,9 @@ function update_ssh_config {
         echo "Ok." | tee -a ${LOG_FILE}
 
         # Replace node-2 entry
-        echo "private_data_ip_node_2: $private_data_ip_node_2"
+        echo "Private n/w IP (Server B): $pvt_ip_b"
         echo -n "Updating server B hostname in ssh config file of server A..................." 2>&1|tee -a ${LOG_FILE}
-        local secondary_host=$(ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "hostname")
+        local secondary_host=$(ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "hostname")
         # echo ${secondary_host}
         local line_to_replace=$(grep -m2 -noP "HostName" /root/.ssh/config|tail -1|cut -d: -f1)
         # echo ${line_to_replace}
@@ -73,10 +68,10 @@ function update_ssh_config {
         sed -i "${line_to_replace}s|HostName.*|HostName ${secondary_host}|" /root/.ssh/config
         echo "Ok." | tee -a ${LOG_FILE}
     else
-        echo "private_data_ip_node_1: $private_data_ip_node_1"
+        echo "Private n/w IP (Server A): $pvt_ip_a"
         echo -n "Updating server B hostname in ssh config file of server B..................." 2>&1|tee -a ${LOG_FILE}
         # Replace node-1 entry
-        local primary_host=$(ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_1} "hostname")
+        local primary_host=$(ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_a} "hostname")
         # echo ${primary_host}
         local line_to_replace=$(grep -m1 -noP "HostName" /root/.ssh/config|tail -1|cut -d: -f1)
         # echo ${line_to_replace}
@@ -102,7 +97,7 @@ function update_salt_minion {
         # Getting '127.0.0.1'. This can be hard-coded also
         local localhost_ip=$(awk '{print $1; exit}' /etc/hosts)
         local primary_host=$(hostname)
-        local secondary_host=$(ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "hostname")
+        local secondary_host=$(ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "hostname")
         # echo ${secondary_host}
         local line_to_replace=$(grep -m1 -noP "master: " /etc/salt/minion|tail -1|cut -d: -f1)
         # echo ${line_to_replace}
@@ -112,7 +107,7 @@ function update_salt_minion {
         echo "Ok." | tee -a ${LOG_FILE}
 
         echo -n "Setting salt-master on server B (secondary node)............................" 2>&1|tee -a ${LOG_FILE}
-        ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "sed -i \"${line_to_replace}s|^master:.*|master: \['${primary_host}', '${localhost_ip}'\]|\" /etc/salt/minion"
+        ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "sed -i \"${line_to_replace}s|^master:.*|master: \['${primary_host}', '${localhost_ip}'\]|\" /etc/salt/minion"
         echo "Ok." | tee -a ${LOG_FILE}
         
         # It's safe to restart service on both nodes
@@ -121,7 +116,7 @@ function update_salt_minion {
         echo "Ok." | tee -a ${LOG_FILE}
 
         echo -n "Restarting salt-minion on Server B.........................................." 2>&1|tee -a ${LOG_FILE}
-        ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "systemctl restart salt-minion"
+        ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "systemctl restart salt-minion"
         echo "Ok." | tee -a ${LOG_FILE}
 
         sleep 5
@@ -131,7 +126,7 @@ function update_salt_minion {
         echo "Ok." | tee -a ${LOG_FILE}
 
         echo -n "Restarting salt-master on Server B.........................................." 2>&1|tee -a ${LOG_FILE}
-        ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "systemctl restart salt-master"
+        ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "systemctl restart salt-master"
         echo "Ok." | tee -a ${LOG_FILE}
 
         echo -n "Listing salt keys..........................................................." 2>&1 | tee -a ${LOG_FILE}
@@ -150,16 +145,6 @@ function update_cluster_sls {
     local cluster_vip=${2:-}
     local _static_ip_a=${3:-}
     local _static_ip_b=${4:-}
-
-    #local _cluster_sls_path=${PRVSNR_ROOT}/pillar/components/cluster.sls
-    #if [[ -f "/var/lib/seagate/cortx/provisioner/shared/srv/pillar/groups/all/uu_cluster.sls" ]]; then
-    #    _cluster_sls_path=/var/lib/seagate/cortx/provisioner/shared/srv/pillar/groups/all/uu_cluster.sls
-    #elif [[ -f "/srv/glusterfs/volume_prvsnr_data/srv/pillar/groups/all/uu_cluster.sls" ]]; then
-    #    _cluster_sls_path=/srv/glusterfs/volume_prvsnr_data/srv/pillar/groups/all/uu_cluster.sls
-    #else
-    #    echo "ERROR: Cluster data is not updated correctly" >> ${LOG_FILE}
-    #    exit 1
-    #fi
 
     if [[ "srvnode-1" == "$(cat /etc/salt/minion_id)" ]]; then
         echo -n "Updating Management VIP in pillar..........................................." 2>&1|tee -a ${LOG_FILE}
@@ -194,39 +179,47 @@ function update_cluster_sls {
         # Hostname
         local primary_host=$(hostname)
         echo "DEBUG:primary_host: ${primary_host}" >> ${LOG_FILE}
-        #local line_to_replace=$(grep -m1 -n "srvnode-1:" ${_cluster_sls_path}|tail -1|cut -d: -f1)
-        #echo "DEBUG: line_to_replace: ${line_to_replace}" >> ${LOG_FILE}
-        #sed -i "${line_to_replace},/hostname:*/ s|hostname:.*|hostname: ${primary_host}|" ${_cluster_sls_path}
         provisioner pillar_set cluster/srvnode-1/hostname \"${primary_host}\"
         echo "Ok." | tee -a ${LOG_FILE}
         # BMC IP-address
-        # grep -m1 -A10 -n "srvnode-1:" ${_cluster_sls_path}|grep -m1 -A3 "bmc"|grep -m1 "ip"|cut -d: -f2|tr -d [:space:]
-        # sed -i "${line_to_replace},/ip:*/ s|ip:.*|ip: ${primary_host}|" ${_cluster_sls_path}
-        # echo "Updated cluster.sls for node-1 hostname on primary node" 2>&1|tee -a ${LOG_FILE}
         (hostnamectl status | grep Chassis | grep -q server) && {
             echo -n "Fetching and updating BMC IP for Server A..................................." 2>&1|tee -a ${LOG_FILE}
-            update_bmc_ip "srvnode-1" >> ${LOG_FILE}
+            #update_bmc_ip "srvnode-1" >> ${LOG_FILE}
+            _ip_line=$(ipmitool lan print 1|grep -oP 'IP Address.+:.*\d+')
+            _ip=$(echo ${_ip_line}|cut -f2 -d':'|tr -d ' ')
+            if [[ -n "$_ip" && "$_ip" != "0.0.0.0" ]]; then
+                echo "BMC_IP (Server A): ${_ip}" >> ${LOG_FILE}
+                provisioner pillar_set cluster/srvnode-1/bmc:ip \"${_ip}\"
+            else
+                echo "ERROR: BMC_IP is not configured on Server A" | tee -a ${LOG_FILE}
+                exit 1
+            fi
             echo "Ok." | tee -a ${LOG_FILE}
+            echo "BMC_IP (Server A): ${_ip}" | tee -a ${LOG_FILE}
         }
 
         # Replace node-2 entry
         # Hostname
         echo -n "Updating hostname of Server B..............................................." 2>&1|tee -a ${LOG_FILE}
-        local secondary_host=$(ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "hostname")
+        local secondary_host=$(ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "hostname")
         echo "DEBUG: secondary_host: ${secondary_host}" >> ${LOG_FILE}
-        #local line_to_replace=$(grep -m1 -n "srvnode-2:" ${_cluster_sls_path}|tail -1|cut -d: -f1)
-        #echo "DEBUG: line_to_replace: ${line_to_replace}" >> ${LOG_FILE}
-        #sed -i "${line_to_replace},/hostname:*/ s|hostname:.*|hostname: ${secondary_host}|" ${_cluster_sls_path}
         provisioner pillar_set cluster/srvnode-2/hostname \"${secondary_host}\"
         echo "Ok." | tee -a ${LOG_FILE}
         # BMC IP-address
-        # grep -m1 -A10 -n "srvnode-2:" ${_cluster_sls_path}|grep -m1 -A3 "bmc"|grep -m1 "ip"|cut -d: -f2|tr -d [:space:]
-        # sed -i "${line_to_replace},/ip:*/ s|ip:.*|ip: ${primary_host}|" ${_cluster_sls_path}
-        # echo "Updated cluster.sls for node-1 hostname on primary node" 2>&1|tee -a ${LOG_FILE}
         (hostnamectl status | grep Chassis | grep -q server) && {
             echo -n "Fetching and updating BMC IP for Server B..................................." 2>&1|tee -a ${LOG_FILE}
-            update_bmc_ip "srvnode-2" "srvnode-2" >> ${LOG_FILE}
+            #update_bmc_ip "srvnode-2" "srvnode-2" >> ${LOG_FILE}
+            _ip_line=$(${ssh_cmd} ${pvt_ip_b} ipmitool lan print 1|grep -oP 'IP Address.+:.*\d+')
+            _ip=$(echo ${_ip_line}|cut -f2 -d':'|tr -d ' ')
+            if [[ -n "$_ip" && "$_ip" != "0.0.0.0" ]]; then
+                echo "BMC_IP (Server B): ${_ip}" >> ${LOG_FILE}
+                provisioner pillar_set cluster/srvnode-2/bmc:ip \"${_ip}\"
+            else
+                echo "ERROR: BMC_IP is not configured on Server B" | tee -a ${LOG_FILE}
+                exit 1
+            fi
             echo "Ok." | tee -a ${LOG_FILE}
+            echo "BMC_IP (Server B): ${_ip}" | tee -a ${LOG_FILE}
         }
 
         echo -n "Refreshing Salt pillar from Server A........................................" 2>&1|tee -a ${LOG_FILE}
@@ -243,6 +236,7 @@ function recover_rabbitmq_cluster {
     salt "srvnode-2" state.apply components.misc_pkgs.rabbitmq ${salt_opts}; sleep 5
     echo "Done"
 }
+
 
 
 function lock_unboxing_user {
diff --git a/cli/src/factory_ops/unboxing/system_check b/cli/src/factory_ops/unboxing/system_check
--- a/cli/src/factory_ops/unboxing/system_check
+++ b/cli/src/factory_ops/unboxing/system_check
@@ -56,12 +56,6 @@ function trap_handler {
 }
 trap trap_handler ERR
 
-#export private_data_ip_node_1=$(get_pillar_data cluster:srvnode-1:network:data_nw:pvt_ip_addr)
-#export private_data_ip_node_2=$(get_pillar_data cluster:srvnode-2:network:data_nw:pvt_ip_addr)
-
-export private_data_ip_node_1="${pvt_ip_a:-"192.168.0.1"}"
-export private_data_ip_node_2="${pvt_ip_b:-"192.168.0.2"}"
-
 function check_boxing_flag {
     if [[ -f '/opt/seagate/cortx/provisioner/generated_config/boxed' ]]
     then
@@ -89,7 +83,7 @@ function check_salt_services {
     # Check salt-minion on secondary node.
     local node_2_private_data_ip=$(grep -m2 -A8 -P "data_nw:" ${cluster_sls_path}|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
     if [[ -z ${node_2_private_data_ip} ]]; then
-        node_2_private_data_ip=${private_data_ip_node_2}
+        node_2_private_data_ip=${pvt_ip_b}
     fi
     if ! (ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${node_2_private_data_ip} "systemctl status salt-master>/dev/null"); then
         ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${node_2_private_data_ip} "systemctl start salt-minion"
@@ -101,21 +95,21 @@ function check_hostname {
     hostname 2>&1|tee -a ${LOG_FILE}
 
     echo -n "      Hostname (Server B)      : " |tee -a ${LOG_FILE}
-    ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "hostname" 2>&1|tee -a ${LOG_FILE}
+    ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "hostname" 2>&1|tee -a ${LOG_FILE}
 }
 
 function check_pvt_data_connectivity {
     local private_data_if=$(grep -m1 -A5 -P "data_nw:" ${cluster_sls_path}|grep -A2 "iface:"|tail -1|cut -d'-' -f2|tr -d "[:space:]")
-    echo "      pvt nw IP (Server A)     : $private_data_ip_node_1" | tee -a ${LOG_FILE}
-    echo "      pvt nw IP (Server B)     : $private_data_ip_node_2" | tee -a ${LOG_FILE}
+    echo "      Private n/w IP (Server A)     : $pvt_ip_a" | tee -a ${LOG_FILE}
+    echo "      Private n/w IP (Server B)     : $pvt_ip_b" | tee -a ${LOG_FILE}
     echo -n "Checking connectivity from server A to server B over private network........" | tee -a ${LOG_FILE}
     # node1 => node2: private data interface
-    ping -c1 -W2 -I${private_data_if} ${private_data_ip_node_2} > /dev/null || (echo "ERROR: Unable to ping srvnode-2 from srvnode-1, over ${private_data_if}" |tee -a ${LOG_FILE}; exit 1)
+    ping -c1 -W2 -I${private_data_if} ${pvt_ip_b} > /dev/null || (echo "ERROR: Unable to ping srvnode-2 from srvnode-1, over ${private_data_if}" |tee -a ${LOG_FILE}; exit 1)
     echo "Ok." | tee -a ${LOG_FILE}
 
     echo -n "Checking connectivity from server B to server A over private network........" | tee -a ${LOG_FILE}
     # node2 => node1: private data interface
-    ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "ping -c1 -W2 -I${private_data_if} ${private_data_ip_node_1}" > /dev/null || (echo "ERROR: Unable to ping srvnode-1 from srvnode-2, over ${private_data_if}" |tee -a ${LOG_FILE}; exit 1)
+    ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "ping -c1 -W2 -I${private_data_if} ${pvt_ip_b}" > /dev/null || (echo "ERROR: Unable to ping srvnode-1 from srvnode-2, over ${private_data_if}" |tee -a ${LOG_FILE}; exit 1)
     echo "Ok." | tee -a ${LOG_FILE}
 }
 
@@ -147,11 +141,11 @@ function check_mgmt_ip {
 
     # Node-2 IPs
     # ip for mgmt interface
-    local mgmt_ip_2=$((ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "ip addr show dev ${mgmt_if}|grep inet|grep -v inet6|grep -Po \"\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\"" || (echo "ERROR: IP address missing for ${mgmt_if} on srvnode-2" | tee -a ${LOG_FILE}; echo 1))|head -1)
+    local mgmt_ip_2=$((ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "ip addr show dev ${mgmt_if}|grep inet|grep -v inet6|grep -Po \"\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\"" || (echo "ERROR: IP address missing for ${mgmt_if} on srvnode-2" | tee -a ${LOG_FILE}; echo 1))|head -1)
     echo "      Management IP (Server B) : ${mgmt_ip_2}" | tee -a ${LOG_FILE}
 
     # ip for public data interface
-    # local public_data_ip_2=$(ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "ip addr show dev ${public_data_if}|grep inet|grep -v inet6|grep -Po \"\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\"|head -1")
+    # local public_data_ip_2=$(ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "ip addr show dev ${public_data_if}|grep inet|grep -v inet6|grep -Po \"\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\"|head -1")
     # echo ${public_data_ip_2}
 
     # Start ping test
@@ -163,7 +157,7 @@ function check_mgmt_ip {
 
     # node2 => node1: private data interface
     echo -n "Checking connectivity from server B to server A over management network....." | tee -a ${LOG_FILE}
-    ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "ping -c1 -W2 -I${mgmt_if} ${mgmt_ip_1}" > /dev/null || (echo "ERROR: Unable to ping srvnode-1 from srvnode-2, over ${mgmt_if}" |tee -a ${LOG_FILE}; exit 1)
+    ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${pvt_ip_b} "ping -c1 -W2 -I${mgmt_if} ${mgmt_ip_1}" > /dev/null || (echo "ERROR: Unable to ping srvnode-1 from srvnode-2, over ${mgmt_if}" |tee -a ${LOG_FILE}; exit 1)
     echo "Ok." | tee -a ${LOG_FILE}
 }
 
