EOS-13740: Remove target_build from release pillar during unboxing.
Signed-off-by: Pritam Bhavsar <pritam.bhavsar@seagate.com>

diff --git a/cli/src/factory_ops/unboxing/config_update b/cli/src/factory_ops/unboxing/config_update
--- a/cli/src/factory_ops/unboxing/config_update
+++ b/cli/src/factory_ops/unboxing/config_update
@@ -194,6 +194,41 @@ function update_cluster_sls {
     fi
 }
 
+function remove_target_build {
+
+    echo "Removing CORTX build url from configuration" | tee -a ${LOG_FILE}
+    local _release_sls_path=${PRVSNR_ROOT}/pillar/components/release.sls
+    echo "Removing target_build from $_release_sls_path" >> $LOG_FILE
+    line_target_build=`grep -n "target_build:"  $_release_sls_path | cut -d: -f1`
+    sed -ie "${line_target_build}s/.*/    target:_build:/" $_release_sls_path
+
+    if [[ -f "${PRVSNR_ROOT}/pillar/user/groups/all/release.sls" ]]; then
+        local _release_sls_path_user=${PRVSNR_ROOT}/pillar/user/groups/all/release.sls
+        echo "Removing target_build from $_release_sls_path_user" >> $LOG_FILE
+        line_target_build=`grep -n "target_build:"  $_release_sls_path_user | cut -d: -f1`
+        sed -ie "${line_target_build}s/.*/    target:_build:/" $_release_sls_path_user
+    fi
+
+    echo "Refreshing Salt pillars" >> ${LOG_FILE}
+    salt '*' saltutil.refresh_pillar ${salt_opts}
+    echo "Checking if the target_bulid url is removed from release pillar" >> ${LOG_FILE}
+
+    _node1_tgt_build=$(salt srvnode-1 pillar.get eos_release:target_build --output=newline_values_only ${salt_opts})
+    _node2_tgt_build=$(salt srvnode-2 pillar.get eos_release:target_build --output=newline_values_only ${salt_opts})
+    if [[ ! -z "$_node1_tgt_build" ]]; then
+        echo "ERROR: Target build url could not be reset on srvnode-1" | tee -a ${LOG_FILE}
+        exit 1
+    fi
+
+    if [[ ! -z "$_node2_tgt_build" ]]; then
+        echo "ERROR: Target build url could not be reset on srvnode-2" | tee -a ${LOG_FILE}
+        exit 1
+    fi
+
+    echo "target_bulid url is removed from release pillar" >> ${LOG_FILE}
+    echo "Done" | tee -a ${LOG_FILE}
+}
+
 function recover_rabbitmq_cluster {
     # # Update RabbitMQ cluster
     echo -n "Starting rabbitmq cluster......" 2>&1|tee -a ${LOG_FILE}
