EOS-6418: Unboxing with BMC IP update logic

diff --git a/cli/src/factory_ops/unboxing/config_update b/cli/src/factory_ops/unboxing/config_update
--- a/cli/src/factory_ops/unboxing/config_update
+++ b/cli/src/factory_ops/unboxing/config_update
@@ -5,24 +5,36 @@
 #   2. Update cluster.sls with hostnames obtained for node-1 and node-2 
 #   3. Update /etc/salt/minion for hostname
 #   4. Start rabbitmq cluster   <= Currently handled in init
-set -eu
+set -euE
+
+BASEDIR=$(dirname "${BASH_SOURCE}")
+
+. ${BASEDIR}/../utils
+. ${BASEDIR}/../../functions.sh
 
 export PRVSNR_ROOT="/opt/seagate/eos-prvsnr"
 export LOG_FILE="${LOG_FILE:-/var/log/seagate/provisioner/unboxing_config_update.log}"
 truncate -s 0 ${LOG_FILE}
 
-export private_data_ip_node_1=$(grep -m1 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/components/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
-export private_data_ip_node_2=$(grep -m2 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/components/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
+# export private_data_ip_node_1=$(grep -m1 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
+# export private_data_ip_node_2=$(grep -m2 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
+export private_data_ip_node_1=$(get_pillar_data cluster:srvnode-1:network:data_nw:pvt_ip_addr)
+export private_data_ip_node_2=$(get_pillar_data cluster:srvnode-2:network:data_nw:pvt_ip_addr)
+
+function trap_handler {
+  echo "For detailed error logs, please see: $LOG_FILE"
+}
+trap trap_handler ERR
 
 function update_ssh_config {
-    if [[ "eosnode-1" == $(cat /etc/salt/minion_id) ]]; then
+    if [[ "srvnode-1" == $(cat /etc/salt/minion_id) ]]; then
         echo "Updating localhost in /root/.ssh/config on primary node"|tee -a ${LOG_FILE}
         # Replace node-1 entry
         local primary_host=$(hostname)
         # echo ${primary_host}
         local line_to_replace=$(grep -m1 -noP "HostName" /root/.ssh/config|tail -1|cut -d: -f1)
         # echo ${line_to_replace}
-        sed -i "s|Host eosnode-1.*|Host eosnode-1 ${primary_host}|" /root/.ssh/config
+        sed -i "s|Host srvnode-1.*|Host srvnode-1 ${primary_host}|" /root/.ssh/config
         sed -i "${line_to_replace}s|HostName.*|HostName ${primary_host}|" /root/.ssh/config
         echo "Updated localhost in /root/.ssh/config on primary node"|tee -a ${LOG_FILE}
 
@@ -32,7 +44,7 @@ function update_ssh_config {
         # echo ${secondary_host}
         local line_to_replace=$(grep -m2 -noP "HostName" /root/.ssh/config|tail -1|cut -d: -f1)
         # echo ${line_to_replace}
-        sed -i "s|Host eosnode-2.*|Host eosnode-2 ${secondary_host}|" /root/.ssh/config
+        sed -i "s|Host srvnode-2.*|Host srvnode-2 ${secondary_host}|" /root/.ssh/config
         sed -i "${line_to_replace}s|HostName.*|HostName ${secondary_host}|" /root/.ssh/config
         echo "Updated remote host in /root/.ssh/config on primary node"|tee -a ${LOG_FILE}
     else
@@ -42,7 +54,7 @@ function update_ssh_config {
         # echo ${primary_host}
         local line_to_replace=$(grep -m1 -noP "HostName" /root/.ssh/config|tail -1|cut -d: -f1)
         # echo ${line_to_replace}
-        sed -i "s|Host eosnode-1.*|Host eosnode-1 ${primary_host}|" /root/.ssh/config
+        sed -i "s|Host srvnode-1.*|Host srvnode-1 ${primary_host}|" /root/.ssh/config
         sed -i "${line_to_replace}s|HostName.*|HostName ${primary_host}|" /root/.ssh/config
         echo "Updated localhost in /root/.ssh/config on secondary node"|tee -a ${LOG_FILE}
 
@@ -52,7 +64,7 @@ function update_ssh_config {
         # echo ${secondary_host}
         local line_to_replace=$(grep -m2 -noP "HostName" /root/.ssh/config|tail -1|cut -d: -f1)
         # echo ${line_to_replace}
-        sed -i "s|Host eosnode-2.*|Host eosnode-2 ${secondary_host}|" /root/.ssh/config
+        sed -i "s|Host srvnode-2.*|Host srvnode-2 ${secondary_host}|" /root/.ssh/config
         sed -i "${line_to_replace}s|HostName.*|HostName ${secondary_host}|" /root/.ssh/config
         echo "Updated remote host in /root/.ssh/config on secondary node"|tee -a ${LOG_FILE}
     fi
@@ -60,7 +72,7 @@ function update_ssh_config {
 
 function update_salt_minion {
 
-    if [[ "eosnode-1" == $(cat /etc/salt/minion_id) ]]; then
+    if [[ "srvnode-1" == $(cat /etc/salt/minion_id) ]]; then
         local host=$(hostname)
         local line_to_replace=$(grep -m1 -noP "master: " /etc/salt/minion|tail -1|cut -d: -f1)
         # echo ${line_to_replace}
@@ -89,24 +101,45 @@ function update_salt_minion {
 }
 
 function update_cluster_sls {
-    if [[ "eosnode-1" == $(cat /etc/salt/minion_id) ]]; then
+    local _cluster_sls_path=${PRVSNR_ROOT}/pillar/components/cluster.sls
+    if [[ -f "${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls" ]]; then
+        _cluster_sls_path=${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls
+    fi
+
+    if [[ "srvnode-1" == $(cat /etc/salt/minion_id) ]]; then
         echo "Updating cluster.sls for node-1 hostname on primary node"|tee -a ${LOG_FILE}
         # Replace node-1 entry
+        # Hostname
         local primary_host=$(hostname)
         # echo ${primary_host}
-        local line_to_replace=$(grep -m1 -noP "eosnode-1:" ${PRVSNR_ROOT}/pillar/components/cluster.sls|tail -1|cut -d: -f1)
+        local line_to_replace=$(grep -m1 -n "srvnode-1:" ${_cluster_sls_path}|tail -1|cut -d: -f1)
         # echo ${line_to_replace}
-        sed -i "${line_to_replace},/hostname:*/ s|hostname:.*|hostname: ${primary_host}|" ${PRVSNR_ROOT}/pillar/components/cluster.sls
+        sed -i "${line_to_replace},/hostname:*/ s|hostname:.*|hostname: ${primary_host}|" ${_cluster_sls_path}
         echo "Updated cluster.sls for node-1 hostname on primary node"|tee -a ${LOG_FILE}
+        # BMC IP-address
+        # grep -m1 -A10 -n "srvnode-1:" ${_cluster_sls_path}|grep -m1 -A3 "bmc"|grep -m1 "ip"|cut -d: -f2|tr -d [:space:]
+        # sed -i "${line_to_replace},/ip:*/ s|ip:.*|ip: ${primary_host}|" ${_cluster_sls_path}
+        # echo "Updated cluster.sls for node-1 hostname on primary node"|tee -a ${LOG_FILE}
+        (hostnamectl status | grep Chassis | grep -q server) && {
+            update_bmc_ip "srvnode-1"
+        }
 
         # Replace node-2 entry
+        # Hostname
         echo "Updating cluster.sls for node-2 hostname on primary node"|tee -a ${LOG_FILE}
         local secondary_host=$(ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "hostname")
         # echo ${secondary_host}
-        local line_to_replace=$(grep -m1 -noP "eosnode-2:" ${PRVSNR_ROOT}/pillar/components/cluster.sls|tail -1|cut -d: -f1)
+        local line_to_replace=$(grep -m1 -n "srvnode-2:" ${_cluster_sls_path}|tail -1|cut -d: -f1)
         # echo ${line_to_replace}
-        sed -i "${line_to_replace},/hostname:*/ s|hostname:.*|hostname: ${secondary_host}|" ${PRVSNR_ROOT}/pillar/components/cluster.sls
+        sed -i "${line_to_replace},/hostname:*/ s|hostname:.*|hostname: ${secondary_host}|" ${_cluster_sls_path}
         echo "Updated cluster.sls for node-2 hostname on primary node"|tee -a ${LOG_FILE}
+        # BMC IP-address
+        # grep -m1 -A10 -n "srvnode-2:" ${_cluster_sls_path}|grep -m1 -A3 "bmc"|grep -m1 "ip"|cut -d: -f2|tr -d [:space:]
+        # sed -i "${line_to_replace},/ip:*/ s|ip:.*|ip: ${primary_host}|" ${_cluster_sls_path}
+        # echo "Updated cluster.sls for node-1 hostname on primary node"|tee -a ${LOG_FILE}
+        (hostnamectl status | grep Chassis | grep -q server) && {
+            update_bmc_ip "srvnode-2" "srvnode-2"
+        }
 
         echo "Refreshing salt pillar from primary node"|tee -a ${LOG_FILE}
         sleep 5
@@ -117,11 +150,22 @@ function update_cluster_sls {
 
 function recover_rabbitmq_cluster {
     # # Update RabbitMQ cluster
-    # salt "eosnode-1" state.apply components.misc_pkgs.rabbitmq
-    # salt "eosnode-2" state.apply components.misc_pkgs.rabbitmq
+    salt "srvnode-1" state.apply components.misc_pkgs.rabbitmq
+    salt "srvnode-2" state.apply components.misc_pkgs.rabbitmq
 
     # # Update SSPL init
-    # salt "*" state.apply components.s3server.config
-    # salt "*" state.apply components.sspl.config
-    # salt "*" state.apply components.csm.config
+    salt "*" state.apply components.s3server.config
+    salt "*" state.apply components.sspl.config
+    salt "*" state.apply components.csm.config
+}
+
+function remove_boxing_flag {
+    if [[ -f '/opt/seagate/cortx/provisioner/generated_config/boxed' ]]
+    then
+        echo "INFO: Boxed file found. Removing boxed file." | tee ${LOG_FILE}
+        rm -f /opt/seagate/cortx/provisioner/generated_config/boxed
+    else
+        echo "ERROR: Boxed file not found. Cannot initiate unboxing sequence." | tee ${LOG_FILE}
+        exit 1
+    fi
 }
