Structural changes to source files
Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

diff --git a/cli/src/factory_ops/unboxing/network_init b/cli/src/factory_ops/unboxing/network_init
--- a/cli/src/factory_ops/unboxing/network_init
+++ b/cli/src/factory_ops/unboxing/network_init
@@ -45,9 +45,36 @@ BASEDIR=$(dirname "${BASH_SOURCE}")
 . ${BASEDIR}/network/management
 . ${BASEDIR}/network/public_data
 
-export LOG_FILE="${LOG_FILE:-/var/log/seagate/provisioner/unboxing_nw_update.log}"
+LOG_FILE="${LOG_FILE:-/var/log/seagate/provisioner/unboxing_nw_update.log}"
 mkdir -p $(dirname "${LOG_FILE}")
 #truncate -s 0 ${LOG_FILE}
+
+
+function trap_handler {
+    exit_code=$?
+
+    echo "*************** ERROR! ***************" | tee -a ${LOG_FILE}
+    echo "For detailed error logs, please see: $LOG_FILE" | tee -a ${LOG_FILE}
+    echo "**************************************" | tee -a ${LOG_FILE}
+    
+    # exit $exit_code
+}
+trap trap_handler ERR
+
+
+function intrpt_handler {
+    exit_code=$?
+
+    echo "*************** ERROR! ***************" | tee -a ${LOG_FILE}
+    echo "------------------------------------------------------------------" | tee -a ${LOG_FILE}
+    echo "Received Ctrl-c signal, exiting Gracefully. | tee -a ${LOG_FILE}
+    echo "For detailed logs, please see: $LOG_FILE | tee -a ${LOG_FILE}
+    echo "------------------------------------------------------------------" | tee -a ${LOG_FILE}
+    echo "**************************************" | tee -a ${LOG_FILE}
+
+    # exit $exit_code
+}
+trap intrpt_handler SIGTERM SIGINT
 
 
 # 1.  Accept user choice: DHCP/Static
