EOS-6418: Unboxing with BMC IP update logic

diff --git a/cli/src/factory_ops/unboxing/system_check b/cli/src/factory_ops/unboxing/system_check
--- a/cli/src/factory_ops/unboxing/system_check
+++ b/cli/src/factory_ops/unboxing/system_check
@@ -11,14 +11,27 @@
 #       From node-2 
 #       $ ping -c1 -I<public_data_ip> eosnode-1 
 # NOTE: pick value of public_data_ip from cluster.sls
-set -eu
+set -euE
+
+BASEDIR=$(dirname "${BASH_SOURCE}")
+
+. ${BASEDIR}/../utils
 
 export PRVSNR_ROOT="/opt/seagate/eos-prvsnr"
 export LOG_FILE="${LOG_FILE:-/var/log/seagate/provisioner/unboxing_system_check.log}"
 truncate -s 0 ${LOG_FILE}
 
-export private_data_ip_node_1=$(grep -m1 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/components/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
-export private_data_ip_node_2=$(grep -m2 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/components/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
+function trap_handler {
+  echo "For detailed error logs, please see: $LOG_FILE"
+}
+trap trap_handler ERR
+
+
+# export private_data_ip_node_1=$(grep -m1 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
+# export private_data_ip_node_2=$(grep -m2 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
+
+export private_data_ip_node_1=$(get_pillar_data cluster:srvnode-1:network:data_nw:pvt_ip_addr)
+export private_data_ip_node_2=$(get_pillar_data cluster:srvnode-2:network:data_nw:pvt_ip_addr)
 
 function check_boxing_flag {
     if [[ -f '/opt/seagate/cortx/provisioner/generated_config/boxed' ]]
@@ -27,6 +40,27 @@ function check_boxing_flag {
     else
         echo "ERROR: Boxed file not found. Cannot initiate unboxing sequence." | tee ${LOG_FILE}
         exit 1
+    fi
+}
+
+function check_salt_services {
+    # Check salt-master running on primary node.
+    if ! systemctl status salt-master>/dev/null; then
+        systemctl start salt-master
+    fi
+
+    # Check salt-minion on primary node.
+    if ! systemctl status salt-master>/dev/null; then
+        systemctl start salt-minion
+    fi
+
+    # Check salt-minion on secondary node.
+    local node_2_private_data_ip=$(grep -m2 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/components/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
+    if [[ -f "${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls" ]]; then
+        node_2_private_data_ip=$(grep -m2 -A8 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|grep "pvt_ip_addr"|tail -n1|cut -d':' -f2|tr -d "[:space:]")
+    fi
+    if ! (ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${node_2_private_data_ip} "systemctl status salt-master>/dev/null"); then
+        ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${node_2_private_data_ip} "systemctl start salt-minion"
     fi
 }
 
@@ -39,7 +73,7 @@ function check_hostname {
 }
 
 function check_pvt_data_connectivity {
-    local private_data_if=$(grep -m1 -A4 -P "data_nw:" ${PRVSNR_ROOT}/pillar/components/cluster.sls|tail -1|cut -d'-' -f2|tr -d "[:space:]")
+    local private_data_if=$(grep -m1 -A4 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|tail -1|cut -d'-' -f2|tr -d "[:space:]")
     
     # node1 => node2: private data interface
     ping -c1 -W2 -I${private_data_if} ${private_data_ip_node_2} || (echo "ERROR: Unable to ping srvnode-2 from srvnode-1, over ${private_data_if}" |tee ${LOG_FILE}; exit 1)
@@ -52,9 +86,9 @@ function check_mgmt_ip {
     # Although ways to test public data IP are available;
     # Only management IP would be tested as public data IP would be later updated during onboarding.
 
-    local mgmt_if=$(grep -m1 -A3 -P "mgmt_nw:" ${PRVSNR_ROOT}/pillar/components/cluster.sls|tail -1|cut -d'-' -f2|tr -d "[:space:]")
-    # local public_data_if=$(grep -m1 -A3 -P "data_nw:" ${PRVSNR_ROOT}/pillar/components/cluster.sls|tail -1|cut -d'-' -f2|tr -d "[:space:]")
-    # local private_data_if=$(grep -m1 -A4 -P "data_nw:" ${PRVSNR_ROOT}/pillar/components/cluster.sls|tail -1|cut -d'-' -f2|tr -d "[:space:]")
+    local mgmt_if=$(grep -m1 -A3 -P "mgmt_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|tail -1|cut -d'-' -f2|tr -d "[:space:]")
+    # local public_data_if=$(grep -m1 -A3 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|tail -1|cut -d'-' -f2|tr -d "[:space:]")
+    # local private_data_if=$(grep -m1 -A4 -P "data_nw:" ${PRVSNR_ROOT}/pillar/user/groups/all/cluster.sls|tail -1|cut -d'-' -f2|tr -d "[:space:]")
 
     # Node-1 IPs
     # ip for mgmt interface
@@ -81,15 +115,4 @@ function check_mgmt_ip {
 
     # node2 => node1: private data interface
     ssh -i /root/.ssh/id_rsa_prvsnr -o "StrictHostKeyChecking no" ${private_data_ip_node_2} "ping -c1 -W2 -I${mgmt_if} ${mgmt_ip_1}" || (echo "ERROR: Unable to ping srvnode-1 from srvnode-2, over ${mgmt_if}" |tee ${LOG_FILE}; exit 1)
-}
-
-function remove_boxing_flag {
-    if [[ -f '/opt/seagate/cortx/provisioner/generated_config/boxed' ]]
-    then
-        echo "INFO: Boxed file found. Removing boxed file." | tee ${LOG_FILE}
-        rm -f /opt/seagate/cortx/provisioner/generated_config/boxed
-    else
-        echo "ERROR: Boxed file not found. Cannot initiate unboxing sequence." | tee ${LOG_FILE}
-        exit 1
-    fi
 }
