EOS-14135: add unboxing pre-flight checks
- Added below pre-checks in unboxing
    - IP addresses for public data interfaces are set
    - BMC accessibility from both servers
    - Server-A and Server-B can access (ping) Controller-A and
      Controller-B on the enclosure

Signed-off-by: Sanjog Vikram Naik <sanjog.naik@seagate.com>

diff --git a/cli/src/factory_ops/unboxing/system_check b/cli/src/factory_ops/unboxing/system_check
--- a/cli/src/factory_ops/unboxing/system_check
+++ b/cli/src/factory_ops/unboxing/system_check
@@ -19,15 +19,15 @@
 
 
 # Functions in this file address following:
-#   1. Check boxing flag file and proceed only if boxing.<timestamp> file is present 
-#       /opt/seagate/cortx/provisioner/generated_configs/boxing.<timestamp> 
-#   2. Check if IP is available on management network interface on node. Wait till one is obtained. 
-#   3. Check if hostname is available on node. Wait till one is obtained. 
-#   4. Ping across nodes over direct network to check connectivity and fetch peer hostname. Wait till success. 
-#       From node-1 
-#       $ ping -c1 -I<public_data_ip> srvnode-2 
-#       From node-2 
-#       $ ping -c1 -I<public_data_ip> srvnode-1 
+#   1. Check boxing flag file and proceed only if boxing.<timestamp> file is present
+#       /opt/seagate/cortx/provisioner/generated_configs/boxing.<timestamp>
+#   2. Check if IP is available on management network interface on node. Wait till one is obtained.
+#   3. Check if hostname is available on node. Wait till one is obtained.
+#   4. Ping across nodes over direct network to check connectivity and fetch peer hostname. Wait till success.
+#       From node-1
+#       $ ping -c1 -I<public_data_ip> srvnode-2
+#       From node-2
+#       $ ping -c1 -I<public_data_ip> srvnode-1
 # NOTE: pick value of public_data_ip from cluster.sls
 set -euE
 
@@ -117,7 +117,7 @@ function check_mgmt_ip {
             exit 1
         fi
     fi
-    
+
     # Node-1 IPs
     # ip for mgmt interface
     local mgmt_ip_1=$((ip addr show dev ${mgmt_if}|grep inet|grep -v inet6|grep -Po "\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}" || echo "ERROR: IP address missing for ${mgmt_if} on srvnode-1" || (tee -a ${LOG_FILE}; exit 1))|head -1)
@@ -146,3 +146,45 @@ function check_mgmt_ip {
     echo "Ok." | tee -a ${LOG_FILE}
 }
 
+#   prvsnr_check <check>
+#   e.g. prvsnr_check hostnames
+#
+#   Performs provisioner check
+#
+#   Prerequisites:
+#       - The provisioner repo is installed.
+#
+#   Args:
+#       check: check to be performed. The checks are listed in Checks class
+#              in api/python/provisioner/config.py
+function prvsnr_check {
+    # Execute 'provisioner check' cli command with mentioned check
+    local prvsnr_chk_cmd="provisioner check $1"
+    # Perform the check and get the output. Check for any failures.
+    local fail_msg=$(${prvsnr_chk_cmd} | grep "fail")
+
+    # If no failures, check is successful. Else display the failure message
+    if [ -z "${fail_msg}" ]
+    then
+        echo "Ok." | tee -a ${LOG_FILE}
+    else
+        echo -n "ERROR: Command '${prvsnr_chk_cmd}' Failed. " | tee -a ${LOG_FILE}
+        echo ${fail_msg} | tee -a ${LOG_FILE}
+        exit 1
+    fi
+}
+
+function check_public_data_interfaces {
+    echo -n "Checking IP addresses for public data interfaces are set........" | tee -a ${LOG_FILE}
+    prvsnr_check public_data_ip
+}
+
+function check_bmc_accessibility {
+    echo -n "Checking BMC accessibility from both servers........" | tee -a ${LOG_FILE}
+    prvsnr_check bmc_accessibility
+}
+
+function check_controller_ip {
+    echo -n "Checking Server-A and Server-B can access (ping) Controller-A and Controller-B on the enclosure........" | tee -a ${LOG_FILE}
+    prvsnr_check controller_ip
+}
