changes in updateing metadata and disk data deatails in cluster.sls file

diff --git a/cli/src/auto-deploy-eos-vm b/cli/src/auto-deploy-eos-vm
--- a/cli/src/auto-deploy-eos-vm
+++ b/cli/src/auto-deploy-eos-vm
@@ -125,9 +125,9 @@ install_prvsnr_cli()
     echo "Target Node: $target_node" 2>&1|tee -a $LOG_FILE
     if [[ "$target_node" = "srvnode-1" ]]; then
         rpm -qa | grep -q eos && {
-            echo "ERROR: eos packages are already installed"
-            echo "Please clean-up previous installtion from both the nodes and retry"
-            exit 1
+        echo "ERROR: eos packages are already installed"
+        echo "Please clean-up previous installtion from both the nodes and retry"
+        exit 1
         }
 	curl http://ci-storage.mero.colo.seagate.com/releases/eos/uploads/prvsnr_uploads/eos-install-prereqs-vm.sh | bash
 	echo "Installing prvsnr-cli on $target_node" 2>&1|tee -a $LOG_FILE
@@ -136,7 +136,6 @@ install_prvsnr_cli()
         return 0
     else
 	echo "Target Node: $target_node" 2>&1|tee -a $LOG_FILE
-	
 	$remote_cmd <<-EOF
 	    set -eu
 	    rpm -qa | grep -q eos && {
@@ -148,17 +147,16 @@ install_prvsnr_cli()
 	    echo "Installing prvsnr-cli on $target_node" 2>&1|tee -a $LOG_FILE
 	    yum install -y $tgt_build/$(curl -s $tgt_build/|grep eos-prvsnr-cli-1.0.0| sed 's/<\/*[^>]*>//g'|cut -d' ' -f1)
 	    systemctl stop firewalld || true
-
 	EOF
     fi
 }
 
 install_config_prvsnr()
 {   if [[ "$singlenode" == false ]]; then
-	set -eu
-	echo -e "\n\t***** INFO: Installing eos-prvsnr-cli on node-2 *****" 2>&1 | tee -a $LOG_FILE
-	sleep 1
-	install_prvsnr_cli "srvnode-2"
+	    set -eu
+	    echo -e "\n\t***** INFO: Installing eos-prvsnr-cli on node-2 *****" 2>&1 | tee -a $LOG_FILE
+	    sleep 1
+	    install_prvsnr_cli "srvnode-2"
     fi
     echo -e "\n\t***** INFO: Installing eos-prvsnr-cli on node-1*****" 2>&1 | tee -a $LOG_FILE
     sleep 1
@@ -168,13 +166,13 @@ install_config_prvsnr()
     echo -e "\n\t***** INFO: Running setup-provisioner *****" 2>&1 | tee -a $LOG_FILE
     sleep 1
     if [[ "$singlenode" == false ]]; then
-	echo -e "\n\tRunning sh /opt/seagate/eos-prvsnr/cli/setup-provisioner"\
-	        "--srvnode-2='$srvnode_2_host' --repo-src=gitlab VM-fixes" 2>&1 | tee -a $LOG_FILE
-	sh /opt/seagate/eos-prvsnr/cli/setup-provisioner --srvnode-2="$srvnode_2_host" --repo-src=gitlab VM-fixes 2>&1 | tee -a $LOG_FILE
-	echo "Done" 2>&1 | tee -a $LOG_FILE
+	    echo -e "\n\tRunning sh /opt/seagate/eos-prvsnr/cli/setup-provisioner"\
+	            "--srvnode-2='$srvnode_2_host' --repo-src=gitlab VM-fixes" 2>&1 | tee -a $LOG_FILE
+	    sh /opt/seagate/eos-prvsnr/cli/setup-provisioner --srvnode-2="$srvnode_2_host" --repo-src=gitlab VM-fixes 2>&1 | tee -a $LOG_FILE
+	    echo "Done" 2>&1 | tee -a $LOG_FILE
     else
-	echo -e "\n\tRunning sh /opt/seagate/eos-prvsnr/cli/setup-provisioner"\
-	        "-S --salt-master="$srvnode_1_host" --repo-src=gitlab VM-fixes" 2>&1 | tee -a $LOG_FILE
+	    echo -e "\n\tRunning sh /opt/seagate/eos-prvsnr/cli/setup-provisioner"\
+	            "-S --salt-master="$srvnode_1_host" --repo-src=gitlab VM-fixes" 2>&1 | tee -a $LOG_FILE
         sh /opt/seagate/eos-prvsnr/cli/setup-provisioner -S --salt-master="$srvnode_1_host" --repo-src=gitlab VM-fixes 2>&1 | tee -a $LOG_FILE
         echo "Done" 2>&1 | tee -a $LOG_FILE
     fi	
@@ -191,10 +189,10 @@ update_pillar()
     fi
     cp $_cluster_sls_path ${_cluster_sls_path}.org
 	
-	# Update hostname if singlenode
-	if [[ "$singlenode" == false ]]; then
-	    sed -i "s/hostname: srvnode-1/hostname: ${srvnode_1_host}/g" $_cluster_sls_path
-	fi	
+    # Update hostname if singlenode
+    if [[ "$singlenode" == false ]]; then
+        sed -i "s/hostname: srvnode-1/hostname: ${srvnode_1_host}/g" $_cluster_sls_path
+    fi
 	
     # Update Mgmt and data interface
     echo "Update Mgmt and data interface" 2>&1|tee -a $LOG_FILE
@@ -209,16 +207,29 @@ update_pillar()
 	
     # Changing Meta and Data disks based on lsblk
     echo "Changing Meta and Data disks based on lsblk" 2>&1|tee -a $LOG_FILE
-    disks=$(lsblk | grep -E ^v.*"disk" | cut -c1-3 | sed "1 d")
+    disks=$(lsblk | grep -E ^v.*"disk" | cut -c1-3 | sed "1 d");
     meta_disk=0
+    line1=`grep -n -m 1 "sdc" $_cluster_sls_path | cut -f1 -d:`;
+    if [[ "$singlenode" == false ]]; then
+        line2=`grep -n -m 2 "sdc" $_cluster_sls_path | cut -f1 -d: | sed "1 d"`;
+        sed -i "${line2}d" $_cluster_sls_path;
+        line2=$(($line2-1))
+    fi
+    sed -i "${line1}d" $_cluster_sls_path;
+    line1=$(($line1-1))
     for i in $disks
     do
         if [ $meta_disk == 0 ] ; then
-            meta_disk=1
-	    sed -i "s/sdb/${i}/g" $_cluster_sls_path;
-	else
-	    sed -i "s/sdc/${i}/g" $_cluster_sls_path;
-	fi
+            meta_disk=1;
+            sed -i "s/sdb/${i}/g" $_cluster_sls_path;
+        else
+            sed -i "${line1} a \        - \/dev\/${i}" $_cluster_sls_path;
+            line1=$(($line1+1));
+            if [[ "$singlenode" == false ]]; then
+                sed -i "${line2} a \        - \/dev\/${i}" $_cluster_sls_path;
+                line2=$(($line2+1));
+            fi
+        fi
     done
 	
     # Update release.sls
