srvnode_ to srvnode- and related changes.
Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

diff --git a/cli/src/auto-deploy b/cli/src/auto-deploy
--- a/cli/src/auto-deploy
+++ b/cli/src/auto-deploy
@@ -90,7 +90,7 @@ usage()
 {
     echo "\
 Usage:
-auto-deploy { -s <secondary node hostname (srvnode_2)> -p <password for sec node>
+auto-deploy { -s <secondary node hostname (srvnode-2)> -p <password for sec node>
                 -C <cluster-ip> -V <management VIP>
                 -t <target build url for CORTX> [--bundle]
                 [Optional Arguments] }
@@ -153,13 +153,13 @@ while [[ $# -gt 0 ]]; do
         -s)
             srvnode_2_host_opt=true
             [ -z "$2" ] &&
-                echo "Error: srvnode_2 not provided" && exit 1;
+                echo "Error: srvnode-2 not provided" && exit 1;
             srvnode_2_host="$2"
             shift 2 ;;
         -p)
             srvnode_2_passwd_opt=true
             [ -z "$2" ] &&
-                echo "Error: srvnode_2 password not provided" && exit 1;
+                echo "Error: srvnode-2 password not provided" && exit 1;
             srvnode_2_passwd="$2"
             shift 2 ;;
         -C)
@@ -299,7 +299,7 @@ install_prvsnr_cli()
     # Install cortx-prvsnr-cli rpm from cortx-storage and install it on both nodes
     target_node="$1"
     echo "Target Node: $target_node" 2>&1|tee -a $LOG_FILE
-    if [[ "$target_node" = "srvnode_1" ]]; then
+    if [[ "$target_node" = "srvnode-1" ]]; then
         rpm -qa | grep -q cortx && {
             echo "ERROR: cortx packages are already installed"
             echo "Cleaning up the packages"
@@ -346,11 +346,11 @@ install_config_prvsnr()
     set -eu
     echo -e "\n\t***** INFO: Installing cortx-prvsnr-cli on node-2 *****" 2>&1 | tee -a $LOG_FILE
     sleep 1
-    install_prvsnr_cli "srvnode_2"
+    install_prvsnr_cli "srvnode-2"
 
     echo -e "\n\t***** INFO: Installing cortx-prvsnr-cli on node-1*****" 2>&1 | tee -a $LOG_FILE
     sleep 1
-    install_prvsnr_cli "srvnode_1"
+    install_prvsnr_cli "srvnode-1"
 
     # Run setup provisioner
     echo -e "\n\t***** INFO: Running setup-provisioner *****" 2>&1 | tee -a $LOG_FILE
@@ -361,8 +361,8 @@ install_config_prvsnr()
     fi
 
     echo -e "\n\tRunning sh /opt/seagate/cortx/provisioner/cli/setup-provisioner"\
-        "--srvnode_2='$srvnode_2_host' '$tgt_build' $_bundle" 2>&1 | tee -a $LOG_FILE
-    sh /opt/seagate/cortx/provisioner/cli/setup-provisioner --srvnode_2="$srvnode_2_host" "$tgt_build" $_bundle 2>&1 | tee -a $LOG_FILE
+        "--srvnode-2='$srvnode_2_host' '$tgt_build' $_bundle" 2>&1 | tee -a $LOG_FILE
+    sh /opt/seagate/cortx/provisioner/cli/setup-provisioner --srvnode-2="$srvnode_2_host" "$tgt_build" $_bundle 2>&1 | tee -a $LOG_FILE
 
     echo "Done" 2>&1 | tee -a $LOG_FILE
 }
@@ -384,41 +384,41 @@ update_pillar()
     #Update interface names
     if [[ "$pub_din_opt" == true && "$pvt_din_opt" == true ]]; then
         echo "Updating interface names" 2>&1|tee -a $LOG_FILE
-        provisioner pillar_set cluster/srvnode_1/network/data/interfaces [\"${pub_din}\",\ \"${pvt_din}\"]
-        provisioner pillar_set cluster/srvnode_2/network/data/interfaces [\"${pub_din}\",\ \"${pvt_din}\"]
+        provisioner pillar_set cluster/srvnode-1/network/data/interfaces [\"${pub_din}\",\ \"${pvt_din}\"]
+        provisioner pillar_set cluster/srvnode-2/network/data/interfaces [\"${pub_din}\",\ \"${pvt_din}\"]
     fi
 
     #Update interface ips
     if [[ "$pub_dip1_opt" == true ]]; then
         echo "Updating interface ip ($pub_dip1) for node1" 2>&1|tee -a $LOG_FILE
-        provisioner pillar_set cluster/srvnode_1/network/data/public_ip \"${pub_dip1}\"
+        provisioner pillar_set cluster/srvnode-1/network/data/public_ip \"${pub_dip1}\"
     fi
 
     if [[ "$pub_dip2_opt" == true ]]; then
         echo "Updating interface ip ($pub_dip2) for node2" 2>&1|tee -a $LOG_FILE
-        provisioner pillar_set cluster/srvnode_2/network/data/public_ip \"${pub_dip2}\"
+        provisioner pillar_set cluster/srvnode-2/network/data/public_ip \"${pub_dip2}\"
     fi
 
     if [[ "$bmc1_user_opt" == true ]]; then
         #Node1
         echo "Updating BMC user ($bmc1_user) for node-1" 2>&1|tee -a $LOG_FILE
-        provisioner pillar_set cluster/srvnode_1/bmc/user \"${bmc1_user}\"
+        provisioner pillar_set cluster/srvnode-1/bmc/user \"${bmc1_user}\"
     fi
     
     if [[ "$bmc2_user_opt" == true ]]; then
         #Node2
         echo "Updating BMC user ($bmc2_user) for node-2" 2>&1|tee -a $LOG_FILE
-        provisioner pillar_set cluster/srvnode_2/bmc/user \"${bmc2_user}\"
+        provisioner pillar_set cluster/srvnode-2/bmc/user \"${bmc2_user}\"
     fi
 
     if [[ "$bmc1_passwd_opt" == true ]]; then
         echo "Updating BMC password ($bmc1_passwd) for node-1" 2>&1|tee -a $LOG_FILE
-        provisioner pillar_set cluster/srvnode_1/bmc/secret \"${bmc1_passwd}\"
+        provisioner pillar_set cluster/srvnode-1/bmc/secret \"${bmc1_passwd}\"
     fi
     
     if [[ "$bmc2_passwd_opt" == true ]]; then
         echo "Updating BMC password ($bmc2_passwd) for node-2" 2>&1|tee -a $LOG_FILE
-        provisioner pillar_set cluster/srvnode_2/bmc/secret \"${bmc2_passwd}\"
+        provisioner pillar_set cluster/srvnode-2/bmc/secret \"${bmc2_passwd}\"
     fi
 
     #Update storage pillar
@@ -427,25 +427,25 @@ update_pillar()
     #Update controller_ip1
     if [[ "$ctrl_a_ip_opt" == true ]]; then
         echo "Updating controller_ip1" 2>&1|tee -a $LOG_FILE
-        provisioner pillar_set storage/enclosure_1/primary/ip \"${ctrl_a_ip}\"
+        provisioner pillar_set storage/enclosure-1/controller/primary/ip \"${ctrl_a_ip}\"
     fi
 
     #Update controller_ip2
     if [[ "$ctrl_b_ip_opt" == true ]]; then
         echo "Updating controller_ip2" 2>&1|tee -a $LOG_FILE
-        provisioner pillar_set storage/enclosure_1/secondary/ip \"${ctrl_b_ip}\"
+        provisioner pillar_set storage/enclosure-1/controller/secondary/ip \"${ctrl_b_ip}\"
     fi
 
     #Update controller user
     if [[ "$ctrl_user_opt" == true ]]; then
         echo "Updating controller user" 2>&1|tee -a $LOG_FILE
-        provisioner pillar_set storage/enclosure_1/user \"${ctrl_user}\"
+        provisioner pillar_set storage/enclosure-1/controller/user \"${ctrl_user}\"
     fi
 
     #Update controller_passwd
     if [[ "$ctrl_passwd_opt" == true ]]; then
         echo "Updating controller_passwd" 2>&1|tee -a $LOG_FILE
-        provisioner pillar_set storage/enclosure_1/secret \"${ctrl_passwd}\"
+        provisioner pillar_set storage/enclosure-1/controller/secret \"${ctrl_passwd}\"
     fi
 
     # Update s3client.sls
@@ -454,7 +454,7 @@ update_pillar()
 
     echo -e "\n\t ***** DEBUG: Updated pillars *****" 2>&1|tee -a $LOG_FILE
     echo -e "\n\t cluster.sls" 2>&1|tee -a $LOG_FILE
-    salt "srvnode_1" pillar.get cluster 2>&1|tee -a $LOG_FILE
+    salt "srvnode-1" pillar.get cluster 2>&1|tee -a $LOG_FILE
 
 }
 
diff --git a/cli/src/factory_ops/boxing/prov_tasks b/cli/src/factory_ops/boxing/prov_tasks
--- a/cli/src/factory_ops/boxing/prov_tasks
+++ b/cli/src/factory_ops/boxing/prov_tasks
@@ -72,10 +72,10 @@ export hostname_a=$(hostname)
 export hostname_b=$($ssh_cmd ${pvt_ip_b} hostname)
 
 function get_nw_interface_names {
-    interface_mgmt_a=$(salt-call pillar.get cluster:srvnode_1:network:mgmt:interface:0 --output=newline_values_only)
-    interface_data_a=$(salt-call pillar.get cluster:srvnode_1:network:data:interface:0 --output=newline_values_only)
-    interface_mgmt_b=$(salt-call pillar.get cluster:srvnode_2:network:mgmt:interface:0 --output=newline_values_only)
-    interface_data_b=$(salt-call pillar.get cluster:srvnode_2:network:data:interface:0 --output=newline_values_only)
+    interface_mgmt_a=$(salt-call pillar.get cluster:srvnode-1:network:mgmt:interface:0 --output=newline_values_only)
+    interface_data_a=$(salt-call pillar.get cluster:srvnode-1:network:data:interface:0 --output=newline_values_only)
+    interface_mgmt_b=$(salt-call pillar.get cluster:srvnode-2:network:mgmt:interface:0 --output=newline_values_only)
+    interface_data_b=$(salt-call pillar.get cluster:srvnode-2:network:data:interface:0 --output=newline_values_only)
 }
 
 function stop_rabbitmq_cluster {
@@ -113,8 +113,8 @@ function backup_files {
 
 
 function configure_service_port {
-    salt "srvnode_1" state.apply components.system.network.mgmt.service_port ${salt_opts} || (
-        echo "ERROR: Failed to configure service port on srvnode_1." | tee -a ${LOG_FILE}
+    salt "srvnode-1" state.apply components.system.network.mgmt.service_port ${salt_opts} || (
+        echo "ERROR: Failed to configure service port on srvnode-1." | tee -a ${LOG_FILE}
         exit 25
     )
 }
@@ -233,7 +233,7 @@ function reset_vips {
 
     echo "Removing the VIPs from Salt configuration" | tee -a ${LOG_FILE}
     echo "Fetching Data VIP from cluster pillar" >> ${LOG_FILE}
-    current_cip=$(salt 'srvnode_1' pillar.get cluster:cluster_ip --output=newline_values_only)
+    current_cip=$(salt 'srvnode-1' pillar.get cluster:cluster_ip --output=newline_values_only)
     if [[ ! -z $current_cip ]]; then
         echo "Removing Data VIP from cluster pillar" >> ${LOG_FILE}
         provisioner pillar_set cluster/cluster_ip \"\" --logfile --logfile-filename ${LOG_FILE}
@@ -241,7 +241,7 @@ function reset_vips {
         echo "Data VIP already reset from Salt configuration" | tee -a ${LOG_FILE}
     fi
     echo "Fetching Management VIP from cluster pillar" >> ${LOG_FILE}
-    current_vip=$(salt 'srvnode_1' pillar.get cluster:mgmt_vip --output=newline_values_only)
+    current_vip=$(salt 'srvnode-1' pillar.get cluster:mgmt_vip --output=newline_values_only)
     if [[ ! -z $current_vip ]]; then
         echo "Removing Management VIP from cluster pillar" >> ${LOG_FILE}
         provisioner pillar_set cluster/mgmt_vip \"\" --logfile --logfile-filename ${LOG_FILE}
@@ -256,24 +256,24 @@ function reset_pub_data_ips {
     echo "Removing the IPs of public data network from Salt configuration" | tee -a ${LOG_FILE}
 
     echo "Fetching public data IP for server A from cluster pillar" >> ${LOG_FILE}
-    pub_dip1=$(salt 'srvnode_1' pillar.get cluster:srvnode_1/network/data/public_ip --output=newline_values_only)
+    pub_dip1=$(salt 'srvnode-1' pillar.get cluster:srvnode-1/network/data/public_ip --output=newline_values_only)
     if [[ ! -z $pub_dip1 ]]; then
         echo "Removing public data IP for server A from cluster pillar" >> ${LOG_FILE}
-        provisioner pillar_set cluster/srvnode_1/network/data/public_ip \"\" --logfile --logfile-filename ${LOG_FILE}
-        provisioner pillar_set cluster/srvnode_1/network/data/gateway \"\" --logfile --logfile-filename ${LOG_FILE}
-        provisioner pillar_set cluster/srvnode_1/network/data/netmask \"\" --logfile --logfile-filename ${LOG_FILE}
+        provisioner pillar_set cluster/srvnode-1/network/data/public_ip \"\" --logfile --logfile-filename ${LOG_FILE}
+        provisioner pillar_set cluster/srvnode-1/network/data/gateway \"\" --logfile --logfile-filename ${LOG_FILE}
+        provisioner pillar_set cluster/srvnode-1/network/data/netmask \"\" --logfile --logfile-filename ${LOG_FILE}
     else
         echo "Public data IP for server A already reset from Salt configuration" | tee -a ${LOG_FILE}
     fi
 
 
     echo "Fetching public data IP for server B from cluster pillar" >> ${LOG_FILE}
-    pub_dip2=$(salt 'srvnode_1' pillar.get cluster:srvnode_1/network/data/public_ip --output=newline_values_only)
+    pub_dip2=$(salt 'srvnode-1' pillar.get cluster:srvnode-1/network/data/public_ip --output=newline_values_only)
     if [[ ! -z $pub_dip2 ]]; then
         echo "Removing public data IP for server B from cluster pillar" >> ${LOG_FILE}
-        provisioner pillar_set cluster/srvnode_2/network/data/public_ip \"\" --logfile --logfile-filename ${LOG_FILE}
-        provisioner pillar_set cluster/srvnode_2/network/data/gateway \"\" --logfile --logfile-filename ${LOG_FILE}
-        provisioner pillar_set cluster/srvnode_2/network/data/netmask \"\" --logfile --logfile-filename ${LOG_FILE}
+        provisioner pillar_set cluster/srvnode-2/network/data/public_ip \"\" --logfile --logfile-filename ${LOG_FILE}
+        provisioner pillar_set cluster/srvnode-2/network/data/gateway \"\" --logfile --logfile-filename ${LOG_FILE}
+        provisioner pillar_set cluster/srvnode-2/network/data/netmask \"\" --logfile --logfile-filename ${LOG_FILE}
     else
         echo "Public data IP for server B already reset from Salt configuration" | tee -a ${LOG_FILE}
     fi
@@ -290,14 +290,14 @@ function reset_pub_data_ips {
 function reset_pub_mgmt_ips {
     echo "Removing the IPs of public management network from Salt Pillar" | tee -a ${LOG_FILE}
     echo "Removing public management IP for Server A from cluster pillar" >> ${LOG_FILE}
-    provisioner pillar_set cluster/srvnode_1/network/mgmt/public_ip PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
-    provisioner pillar_set cluster/srvnode_1/network/mgmt/gateway PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
-    provisioner pillar_set cluster/srvnode_1/network/mgmt/netmask PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
+    provisioner pillar_set cluster/srvnode-1/network/mgmt/public_ip PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
+    provisioner pillar_set cluster/srvnode-1/network/mgmt/gateway PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
+    provisioner pillar_set cluster/srvnode-1/network/mgmt/netmask PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
 
     echo "Removing public management IP for Server B from cluster pillar" >> ${LOG_FILE}
-    provisioner pillar_set cluster/srvnode_2/network/mgmt/public_ip PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
-    provisioner pillar_set cluster/srvnode_2/network/mgmt/gateway PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
-    provisioner pillar_set cluster/srvnode_2/network/mgmt/netmask PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
+    provisioner pillar_set cluster/srvnode-2/network/mgmt/public_ip PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
+    provisioner pillar_set cluster/srvnode-2/network/mgmt/gateway PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
+    provisioner pillar_set cluster/srvnode-2/network/mgmt/netmask PRVSNR_UNDEFINED --logfile --logfile-filename ${LOG_FILE}
     echo "Done" | tee -a ${LOG_FILE}
 }
 
diff --git a/cli/src/factory_ops/unboxing/system_check b/cli/src/factory_ops/unboxing/system_check
--- a/cli/src/factory_ops/unboxing/system_check
+++ b/cli/src/factory_ops/unboxing/system_check
@@ -25,9 +25,9 @@
 #   3. Check if hostname is available on node. Wait till one is obtained.
 #   4. Ping across nodes over direct network to check connectivity and fetch peer hostname. Wait till success.
 #       From node-1
-#       $ ping -c1 -I<public_data_ip> srvnode_2
+#       $ ping -c1 -I<public_data_ip> srvnode-2
 #       From node-2
-#       $ ping -c1 -I<public_data_ip> srvnode_1
+#       $ ping -c1 -I<public_data_ip> srvnode-1
 # NOTE: pick value of public_data_ip from cluster.sls
 set -euE
 
@@ -95,12 +95,12 @@ function check_pvt_data_connectivity {
     
     # node1 => node2: private data interface
     echo -n "Checking connectivity from server A to server B over private network........" | tee -a ${LOG_FILE}
-    ping -c1 -W2 -I${pvt_ip_a} ${pvt_ip_b} > /dev/null || (echo "ERROR: Unable to ping srvnode_2 from srvnode_1, over ${private_data_if}" |tee -a ${LOG_FILE}; exit 1)
+    ping -c1 -W2 -I${pvt_ip_a} ${pvt_ip_b} > /dev/null || (echo "ERROR: Unable to ping srvnode-2 from srvnode-1, over ${private_data_if}" |tee -a ${LOG_FILE}; exit 1)
     echo "Ok." | tee -a ${LOG_FILE}
 
     echo -n "Checking connectivity from server B to server A over private network........" | tee -a ${LOG_FILE}
     # node2 => node1: private data interface
-    ssh -i /root/.ssh/id_rsa_prvsnr -o ConnectTimeout=5 -o "StrictHostKeyChecking no" ${pvt_ip_b} "ping -c1 -W2 -I${pvt_ip_b} ${pvt_ip_a}" > /dev/null || (echo "ERROR: Unable to ping srvnode_1 from srvnode_2, over ${private_data_if}" |tee -a ${LOG_FILE}; exit 1)
+    ssh -i /root/.ssh/id_rsa_prvsnr -o ConnectTimeout=5 -o "StrictHostKeyChecking no" ${pvt_ip_b} "ping -c1 -W2 -I${pvt_ip_b} ${pvt_ip_a}" > /dev/null || (echo "ERROR: Unable to ping srvnode-1 from srvnode-2, over ${private_data_if}" |tee -a ${LOG_FILE}; exit 1)
     echo "Ok." | tee -a ${LOG_FILE}
 }
 
@@ -120,13 +120,13 @@ function check_mgmt_ip {
 
     # Node-1 IPs
     # ip for mgmt interface
-    local mgmt_ip_1=$((ip addr show dev ${mgmt_if}|grep inet|grep -v inet6|grep -Po "\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}" || echo "ERROR: IP address missing for ${mgmt_if} on srvnode_1" || (tee -a ${LOG_FILE}; exit 1))|head -1)
+    local mgmt_ip_1=$((ip addr show dev ${mgmt_if}|grep inet|grep -v inet6|grep -Po "\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}" || echo "ERROR: IP address missing for ${mgmt_if} on srvnode-1" || (tee -a ${LOG_FILE}; exit 1))|head -1)
     echo "      Management IP (Server A) : ${mgmt_ip_1}" | tee -a ${LOG_FILE}
 
 
     # Node-2 IPs
     # ip for mgmt interface
-    local mgmt_ip_2=$(($ssh_cmd ${pvt_ip_b} "ip addr show dev ${mgmt_if}|grep inet|grep -v inet6|grep -Po \"\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\"" || (echo "ERROR: IP address missing for ${mgmt_if} on srvnode_2" | tee -a ${LOG_FILE}; echo 1))|head -1)
+    local mgmt_ip_2=$(($ssh_cmd ${pvt_ip_b} "ip addr show dev ${mgmt_if}|grep inet|grep -v inet6|grep -Po \"\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\"" || (echo "ERROR: IP address missing for ${mgmt_if} on srvnode-2" | tee -a ${LOG_FILE}; echo 1))|head -1)
     echo "      Management IP (Server B) : ${mgmt_ip_2}" | tee -a ${LOG_FILE}
 
     # ip for public data interface
@@ -137,12 +137,12 @@ function check_mgmt_ip {
     # node1 => node2: mgmt interface
     # node1 => node2: private data interface
     echo -n "Checking connectivity from server A to server B over management network....." | tee -a ${LOG_FILE}
-    ping -c1 -W2 -I${mgmt_if} ${mgmt_ip_2} > /dev/null || (echo "ERROR: Unable to ping srvnode_2 from srvnode_1, over ${mgmt_if}" |tee -a ${LOG_FILE}; exit 1)
+    ping -c1 -W2 -I${mgmt_if} ${mgmt_ip_2} > /dev/null || (echo "ERROR: Unable to ping srvnode-2 from srvnode-1, over ${mgmt_if}" |tee -a ${LOG_FILE}; exit 1)
     echo "Ok." | tee -a ${LOG_FILE}
 
     # node2 => node1: private data interface
     echo -n "Checking connectivity from server B to server A over management network....." | tee -a ${LOG_FILE}
-    ssh -i /root/.ssh/id_rsa_prvsnr -o ConnectTimeout=5 -o "StrictHostKeyChecking no" ${pvt_ip_b} "ping -c1 -W2 -I${mgmt_if} ${mgmt_ip_1}" > /dev/null || (echo "ERROR: Unable to ping srvnode_1 from srvnode_2, over ${mgmt_if}" |tee -a ${LOG_FILE}; exit 1)
+    ssh -i /root/.ssh/id_rsa_prvsnr -o ConnectTimeout=5 -o "StrictHostKeyChecking no" ${pvt_ip_b} "ping -c1 -W2 -I${mgmt_if} ${mgmt_ip_1}" > /dev/null || (echo "ERROR: Unable to ping srvnode-1 from srvnode-2, over ${mgmt_if}" |tee -a ${LOG_FILE}; exit 1)
     echo "Ok." | tee -a ${LOG_FILE}
 }
 
