M5: Replace-node improvements - reboot after mpath.
Signed-off-by: Yashodhan Pise <yashodhan.pise@seagate.com>

diff --git a/cli/src/deploy b/cli/src/deploy
--- a/cli/src/deploy
+++ b/cli/src/deploy
@@ -179,6 +179,36 @@ function options_parser {
     esac
 }
 
+function is_conul_running {
+    count=1
+    while [[ /usr/bin/true ]]; do
+        l_info "Validating availability of hare-consul-agents on nodes."
+        l_info "Attempting every 10 secs..."
+
+        consul_service=$(salt "*" service.status hare-consul-agent-c* --output=json)
+        hca1=$(echo ${consul_service}|jq .[\"srvnode-1\"][\"hare-consul-agent-c1\"]|grep -v null)
+        hca2=$(echo ${consul_service}|jq .[\"srvnode-2\"][\"hare-consul-agent-c2\"]|grep -v null)
+        
+        if [[ true == ${hca1} 
+            && true == ${hca2}
+            ]]; then
+            l_info "Both consul agents found running on respective nodes."
+            break
+        fi
+
+        sleep 10
+        count=$((count + 1))
+
+        # Attempt for 5 mins before giving up
+        if [[ ${count} > 30 ]]; then
+            l_error "Unable to get healthy hare-consul-agent service."
+            l_error "Use command 'pcs status' to further find/analyse the issue."
+            l_error "Aborting further deployment..."
+            exit 1
+        fi
+    done
+}
+
 function run_states {
     local states=${@}
 
@@ -226,13 +256,14 @@ function run_states {
                 || "$state" == "sspl"
                 || "$state" == "csm"
                 || "$state" == "provisioner.backup"
-                # || "$state" == "motr.backup" # TODO: Awaiting EOS-12637 fix
-                # || "$state" == "s3server.backup"
-                # || "$state" == "hare.backup"
-                # || "$state" == "ha.iostack-ha.backup"
-                # || "$state" == "sspl.backup"
-                # || "$state" == "csm.backup"
                 ]]; then
+
+                # Consul takes time to come online after initialization (around 2-3 mins at times)
+                # We need to ensure consul service is available before proceeding
+                # Without a healthy consul service SSPL and CSM shall fail
+                if [[ "$state" == "sspl" ]]; then
+                    is_conul_running
+                fi
 
                 # Execute first on srvnode-2 then on srvnode-1.
                 l_info "Applying 'components.$state' for srvnode-2"
@@ -258,14 +289,14 @@ function run_states {
 
             else
 
-                # if [[ "$state" == "ha.iostack-ha" ]]; then
-                #     sed -i 's/systemd:hare-hax-c1 op stop timeout=30/systemd:hare-hax-c1 op stop timeout=200/g' /opt/seagate/cortx/ha/conf/script/build-ha-io
+                if [[ "$state" == "ha.iostack-ha" ]]; then
+                    sed -i 's/systemd:hare-hax-c1 op stop timeout=30/systemd:hare-hax-c1 op stop timeout=200/g' /opt/seagate/cortx/ha/conf/script/build-ha-io
 
-                #     sed -i 's/systemd:hare-hax-c2 op stop timeout=30/systemd:hare-hax-c2 op stop timeout=200/g' /opt/seagate/cortx/ha/conf/script/build-ha-io
+                    sed -i 's/systemd:hare-hax-c2 op stop timeout=30/systemd:hare-hax-c2 op stop timeout=200/g' /opt/seagate/cortx/ha/conf/script/build-ha-io
 
-                #     sleep 2     # Mindfulness break
-                # fi
-
+                    sleep 2     # Mindfulness break
+                fi
+                
                 l_info "Applying 'components.$state' for both nodes"
                 $cmd salt srvnode-[1,2] state.apply components.$state $salt_opts
                 sleep 2     # Mindfulness break
@@ -274,29 +305,7 @@ function run_states {
                 # We need to ensure consul service is available before proceeding
                 # Without a healthy consul service SSPL and CSM shall fail
                 if [[ "$state" == "ha.iostack-ha" ]]; then
-                    count=1
-                    while [[ /usr/bin/true ]]; do
-                        l_info "Validating availability of hare-consul-agent..."
-
-                        consul_service=$(salt "*" service.status hare-consul-agent-c* --output=json)
-                        hca1=$(echo ${consul_service}|jq .[\"srvnode-1\"][\"hare-consul-agent-c1\"]|grep -v null)
-                        hca2=$(echo ${consul_service}|jq .[\"srvnode-2\"][\"hare-consul-agent-c2\"]|grep -v null)
-                        
-                        if [[ true == ${hca1} 
-                            && true == ${hca2}
-                            ]]; then
-                            l_info "Both consul agents found running on respective nodes."
-                            break
-                        fi
-
-                        sleep 15
-                        count=$((count + 1))
-
-                        if [[ ${count} > 20 ]]; then
-                            l_error "Unable to get healthy hare-consul-agent service. Exiting further deployment..."
-                            exit 1
-                        fi
-                    done
+                    is_conul_running
                 fi
             fi
         done
